### ISSUE TITLE
Close X button in tittlebar don't match with gnome theme.

### ISSUE THREAD

**Issue by arumihsnek** [brummer10/guitarix#101]
Why the X to close the swindow is not the same of other gtk aplications? 
![Captura de pantalla de 2021-12-14 13-29-04](https://user-images.githubusercontent.com/71855845/145998540-3f74b32c-287d-42f8-ad42-b797923d61d2.png)

Thanks for this amazing plugin!

**Comment by brummer10** [comment]
That depend on your desktop manager, guitarix is GTK3 based, when you sue a QT based desktop manager you may need a gtk3 theme like Breeze or Adwaita.
https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications
may help

**Comment by arumihsnek** [comment]
Strange, I have an other theme, but i tried with adwaita too. I'm in gnome wayland, and guitarrix es the only program that show the X like that. Even the qt programs look uniform.

**Comment by brummer10** [comment]
I've no experience with wayland, I've just gnome with X-server, there the guitarix window decoration is the same as all other apps. 
So you may need to find out how to set the window decoration for gtk3 apps under wayland.

**Comment by hfiguiere** [comment]
it's a theming issue - on Guitarix side. Nothing to do with the  graphics subsystem.

**Comment by brummer10** [comment]
How to you come to that conclusion? guitarix does nothing in it's theme for window decoration, and, with other desktop managers using the X-server there is not such a issue.
Window decoration is added by the desktop-manager.

**Comment by hfiguiere** [comment]
If you use Mutter/gnome-shell as a compositor (GNOME default) and Gtk3, the window decorations are influenced by the themeing from inside the app.

**Comment by brummer10** [comment]
As I said, there is nothing inside the guitarix theme files which will influence the window decoration. And, there is no issue under gnome with the X-server. 
If wayland require anything from the app theme file for window decoration, then it should have a mechanism to use a fallback.

**Comment by hfiguiere** [comment]
I checked again and was mistaken, it's only when running using Wayland (the Gdk backend) and how CSD are handled in that case.

**Comment by hfiguiere** [comment]
Another thing I see here is that when the Guitarix window is not in the front, the title bar is dark colour (using the default Guitarix skin)

**This is not a workaround suggesstion**

If you use the gtk inspector, you can change the visual style of that button, using the following CSS rule:

```css
button.close.titlebutton, button.close.titlebutton > image {
}
```

I'll see if I can provide a patch to the skin CSS for Guitarix.

**Comment by brummer10** [comment]
I looked a bit deeper into that, but don't find a other solution (doable from inside the CSS file) then hiding the titelbar complete.
It seems that this one: https://github.com/PCMan/gtk3-nocsd
is the way to go to solve (work around) that issue more general.

**Comment by brummer10** [comment]
A other way is to force Xwayland by start guitarix like this
`env WAYLAND_DISPLAY= guitarix`
