### ISSUE TITLE
Does Gx Redeye Big Chump miss `pprop:notOnGUI`?

### ISSUE THREAD

**Issue by JohannesLorenz** [brummer10/guitarix#102]
The feedback switch is not in the gui file here:
https://github.com/brummer10/guitarix/blob/master/trunk/src/LV2/gx_redeye.lv2/gxredeye_ui.cpp#L206-#L219

But it isn't given the lv2:portProperty pprop:notOnGUI, which probably should have been after this line:
https://github.com/brummer10/guitarix/blob/master/trunk/src/LV2/gx_redeye.lv2/gx_redeye.ttl#L209

Can please someone verify if this is an issue?

Originally reported in LMMS/lmms#6254 by @zonkmachine .

**Comment by brummer10** [comment]
Hi
Thanks for forwarding the issue. You are right, it is missing the pprop:notOnGUI for the feedback port in the Big Chump. I'll fix that. 
regards
hermann

**Comment by zonkmachine** [comment]
Could wait no longer. I added the missing pprop and fixed another issue in https://github.com/brummer10/guitarix/pull/132 :)
