### ISSUE TITLE
Consolidate this repository with sourceforge

### ISSUE THREAD

**Issue by dvzrv** [brummer10/guitarix#108]
Hi!

It's great to see that it is possible to provide tickets here. Unfortunately for users and packagers alike this is very confusing, because the sourceforge issue tracker still exists and is linked to on the website. Meanwhile fixed issues (e.g. #107) are referenced, but they do not relate to the currently still canonical upstream issue tracker, but to this repository.

**Comment by brummer10** [comment]
Hi
I very much prefer the issue tracker on github, just, only the one at sourceforge allow anonymous reports (without registration) that's why I keep it alive. The repository content itself is in sync at any time.

**Comment by dvzrv** [comment]
Hi @brummer10,

this is unfortunately not the case anymore, as the tags have started to drift: https://sourceforge.net/p/guitarix/git/ref/master/tags/.

Can you please consolidate these two places? :)

**Comment by brummer10** [comment]
Hi @dvzrv 
I'm sorry. That have changed in the mean time. Sooner or later I'll delete the Sourceforge repository. It would make much more sense to move any distributed package based on github. I've already marked the Sourceforge repository as obsolete.
