### ISSUE TITLE
Feature: Toggleable knobs

### ISSUE THREAD

**Issue by Nathan-D-R** [brummer10/guitarix#113]
It would be very valuable to be able to toggle between knob states over an adjustable amount of time. (using midi signals of course) For example, toggling from 90% echo to 25% echo over the span of 3 seconds. Please let me know if this exists already and I'm missing it, thanks.

**Comment by brummer10** [comment]
So you mean automation? No, that isn't implemented. 
Such behave could maybe archived with the help of mididings
 https://github.com/dsacre/mididings
