### ISSUE TITLE
Problem with fonts (Guitarix 0.42.1/Debian 11)

### ISSUE THREAD

**Issue by KSluchanko** [brummer10/guitarix#114]
Fonts are not rendered correctly, it displays rectangles with four-digit symbol codes inside in controls' names on the "front panels". Menus and other text are fine.
All dependencies are satisfied, strace not found any errors trying to load fonts.
Cannot load image for unknown reason.

**Comment by brummer10** [comment]
Guitarix using fonts-roboto. Make sure you've installed that.
Other than that there is not much we can do for a 2 years old distributed package.

**Comment by KSluchanko** [comment]
Fonts are installed, I have checked it first.
OK, will try to update to newer version.
