### ISSUE TITLE
Master Volume not working

### ISSUE THREAD

**Issue by jasonstone20** [brummer10/guitarix#115]
I am running Guitarix v0.44.1 and the Master Volume doesn't work.  I can control the volume with the Master Gain. Drive, and Mono Level Out, but the Master Volume doesn't seem to affect the volume level at all, although if I turn it up a lot, I get feedback and then the limiter kicks end and kills the signal.  Not really a huge problem, just wanted to know if this is how things are suppose to work, as the Master Volume used to work on v0.3x.x

**Comment by brummer10** [comment]
That sounds like you've connected gx_head_amp to the system output. Remove that connection so that it is only connected to gx_head_fx. 
To avoid the multi client ports you could try running guitarix from terminal with the "-D" command-line switch.

**Comment by jasonstone20** [comment]
Ok, that worked, thank you very much!

**Comment by jasonstone20** [comment]
Now my guitar tone sounds perfect!  WOW!  Thank you so much!  Looks like I am not going to be needing another guitar amp or effect pedal for a while!  It took me a little while, like a few weeks, to be able to dial in a gain sound with fuzz that didn't have a lot of noise.  The volume issue was the last issue I was having, and now it sounds awesome with the guitar tone going through all the effects.  It wasn't before, and I didn't notice until you gave me the volume fix!  Thank you so much for the awesome program!
