### ISSUE TITLE
(maybe a) files installation issue for colwah

### ISSUE THREAD

**Issue by trebmuh** [brummer10/guitarix#12]
Hi @brummer10, it seems that gx_colwah is missing its manifest.ttl file, and gx_wah seems to only have its ttl file. Even if I saw it while looking at the Debian packaging ([see here](https://packages.debian.org/sid/amd64/guitarix-lv2/filelist)), it could very well be an upstream issue.

Any idea?

**Comment by brummer10** [comment]
Yes, it's a upstream bug introduced by the update to the newer waf. It's fixed in our git repository.

**Comment by trebmuh** [comment]
Thanks for the quick answer.

_(This thread is a duplicate of #2 , my bad.)_
