### ISSUE TITLE
guitarix don't compile with zita-resampler 1.10

### ISSUE THREAD

**Issue by styrsven** [brummer10/guitarix#122]
zita-resampler.py identifies the version of zita-resampler by checking that ZITA_RESAMPLER_MAJOR_VERSION has the value 1, but in version 1.10 ZITA_RESAMPLER_MAJOR_VERSION is not defined in the include files.

**Comment by brummer10** [comment]
Hi
Thanks for reporting the issue. I haven't checked out zita-resampler 1.10 for now.
Still, as we provided zita-resampler included in the source there is no reason to fail at this step. 
So now, when the zita-resampler test fail we'll switch to use the internal version instead refuse compile. 
At some point later I'll implement a check for >1.10
