### ISSUE TITLE
Out of sync with Sourceforge git

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#123]
I just updated Guitarix-git from the AUR, which pulls from the Sourceforge git repository. I had thought that your GitHub and Sourceforge repositories are automatically synced, but the latest commit from Sourceforge is `[b1c686] Fix issue #110 GxTuner Issues` from 2022-05-26.

If you are not keeping the repositories in sync anymore, you might want to inform @gimmeapill so he can change the Guitarix-git pkgbuild file.

**Comment by brummer10** [comment]
Hi @Rippert 
I'm sorry, didn't know that the AUR-git package fetch from sourceforge. That should indeed switch to github. 
As you've ping him here, it should happen soon.  
At some point I'll sync the repository's again, but for now I'm focusing on the guitarix.vst version. 
https://github.com/brummer10/guitarix.vst
Syncing was all time done by hand by me, but the github repository is the main development platform.

**Comment by Rippert** [comment]
Thanks Hermann. I did get the pkgbuild file to work by just changing the download URL from sourceforge to  your Github repo.

I've heard about your VST version. Sounds cool. I'll try it out here soon.

**Comment by Rippert** [comment]
close

**Comment by Rippert** [comment]
I can't seem to close this issue even though I opened it.

**Comment by brummer10** [comment]
Hi @Rippert 
Let's just keep it open as a reminder for me that I need to sync the repositories before the next release. 
Have you seen the new factory presets, there are some special for bass, what do you think of them?

**Comment by Rippert** [comment]
Yes, the new presets are why I wanted to update. Just played with them for a short time earlier today. Really nice. 

A couple of the Bass presets use the Bass enhancer more than I like, but I have pretty good subwoofers and they are probably set up for studio monitors. 

Still, really nice overall. Very good levels and tone. Some of the guitar presets work well for Bass too.

It looks like there are a bunch of new "factory" impulse files in the band folder too, unless I just missed them in my last update. Some really nice sounds. A little hard to tell what to expect from them from the names of the bands but a really good variety to play with. The "Slap" preset uses the convolution plugin and playing with the different files in the band folder gives some really good sounds. They did a good job with the other plugins, the Quad filter, the graphic EQ and the Bright enhancer (don't have the right names in front of me). Really makes the string harmonics pop out. I'll be using that one as a basis for some new custom presets.

Have you ever thought of including a folder of speaker impulses? I know there is a plugin that does some of that, but there are so many possible speakers and it's a little easier to guess what to expect from them from the name of the speaker. I've been using a generic 8x10 impulse on some of my custom presets and it sounds pretty good through a full range PA with a subwoofer.

**Comment by Gimmeapill** [comment]
Thanks guys, I'll update the pkgbuild over the week end (and check also those new presets)

**Comment by brummer10** [comment]
> A couple of the Bass presets use the Bass enhancer more than I like

That was my impression as well. But nice to hear you like them anyway. So do I. 

> It looks like there are a bunch of new "factory" impulse files in the band folder too

No, they are there since ages. Just maybe not so prominent, I know that most people oversee them. 
Within the new vst version they been implemented more prominent. 

> Have you ever thought of including a folder of speaker impulses?

Sure, just it isn't easy to find IR-files under a free license. For the implemented ones by David Fau Casquel, he gives me permission to distribute them under the GPL, I can't find any other IR files which are clearly licenced under a comparable, free license. (Most freebies comes with a restricted, or without any license, so that wouldn't work properly).  Other IR-file creators I asked wouldn't go the full GPL route.

**Comment by Gimmeapill** [comment]
pkgbuild updated

**Comment by Gimmeapill** [comment]
Regarding the presets:
- They are way better than the previous ones, but there are still too much volume variations from one preset to another to my taste.
- The first two Bass presets with the BassEnhancer are terrible, it looks like they were made to blow up speakers. (I did try on studio monitors and a bass amp with the preamp bypassed). There is usually not too much to do to come up with a good bass tone with Guitarix but this is not the way. The third one would be almost usable if the EQ wasn't also all over the place.
- The presets that contain the JCM800 just die at launch, but this is the known issue.

**Comment by 0EVSG** [comment]
Please update the [README.md](https://github.com/brummer10/guitarix#readme) if packagers should switch to github - it's not obvious with it currently declared a mirror of sourceforge.

**Comment by brummer10** [comment]
If you package releases, you could stay at sourceforge as well. I'll sync the repositories before doing a release. 
Only when you provide development snapshots you should point to github, as currently development is going on on github exclusive.

**Comment by Gimmeapill** [comment]
This is absolutely ok: there is nowadays a well maintained official package of the latest stable release in Arch. 
I just checked and it fetches the code from Sourceforge.
Mine is just to track the latest development, so github is indeed the way to go.

**Comment by 0EVSG** [comment]
> If you package releases, you could stay at sourceforge as well. I'll sync the repositories before doing a release.

Good to know, thanks for the clarification. In my case I was looking to backport the build fix 53560efbbc44a971b7b10290d96b059b67c71eed for #122, and couldn't find the commit on sourceforge - so I still think the README can be a bit misleading. Not a big issue though.

**Comment by brummer10** [comment]
I've marked guitarix on Sourcforge now  as obsolete and point to github
