### ISSUE TITLE
Oscilliscope view is backwards

### ISSUE THREAD

**Issue by cassie-is-asleep** [brummer10/guitarix#124]
In the oscilliscope plug-in, the waves are being drawn backwards. [This image here](https://drive.google.com/file/d/1Dbzs7X-PbnpZPw9ae5KpvV01FKHrIvRg/view?usp=sharing) shows a waveform with a distinct left-to-right appearance -- a square-wave with a mid-frequency cut -- in Guitarix and in Audacity. On the oscilliscope plugin, each half wave can be seen having its wide peak first followed by its narrow peak; whereby in audacity, you can see each half wave starting with a narrow peak and then hitting a wide peak.

**Comment by brummer10** [comment]
Hi
I remember I've done that intentional once, but can't remember why. So, I could as well change the direction so that it becomes comparable with other apps. 
Done now, thanks for reporting the issue.
