### ISSUE TITLE
Build fails: error: use of undeclared identifier 'mydsp_faustpower7_f'

### ISSUE THREAD

**Issue by yurivict** [brummer10/guitarix#136]
```
In file included from ../src/LV2/gx_fuzz.lv2/gx_fuzz.cpp:31:
src/LV2/faust/bmfp.cc:148:18: error: use of undeclared identifier 'mydsp_faustpower7_f'
                float fTemp7 = mydsp_faustpower7_f(fTemp6) + fSlow10 * fTemp0 + fTemp6;
                               ^
```

Version: 0.44.1
faust-2.68.1
clang-16
FreeBSD 13.2

**Comment by brummer10** [comment]
Strange, mydsp_faustpower7_f is defined in gx_common line 145:
https://github.com/brummer10/guitarix/blob/master/trunk/src/LV2/DSP/gx_common.h#L145
which is included in gx_fuzz.cpp line 28:
https://github.com/brummer10/guitarix/blob/master/trunk/src/LV2/gx_fuzz.lv2/gx_fuzz.cpp#L28
so before bmfb.cc is included.
