### ISSUE TITLE
0.45.0: Source tarball packs files top-level

### ISSUE THREAD

**Issue by dvzrv** [brummer10/guitarix#143]
Hi! :wave: 

When trying to build 0.45.0 I noticed that the source tarball no longer provides the files in a top-level directory (e.g. `guitarix-0.45.0`) when extracting, but just top-level.

For people building from source this is really quite messy and an anti-pattern as everything below the `trunk/` dir is just extracted to the current working directory!

Can this please be changed for any upcoming release again? :)

**Comment by brummer10** [comment]
Yep, sorry. I need to rewrite the ./waf dist class in order to implement the now needed submodule. Unfortunately the top directory get lost by that. I'll fix that. 
Thanks for the head up
