### ISSUE TITLE
Could not find the program ['msgfmt']

### ISSUE THREAD

**Issue by royi-klein** [brummer10/guitarix#145]
./waf configure --prefix=/usr --includeresampler --includeconvolver --optimization
Setting top to                           : /home/royi/guitar/guitarix/trunk 
Setting out to                           : /home/royi/guitar/guitarix/trunk/build 
Checking for git submodule               : up to date 
Checking for program 'msgfmt'            : not found 
Could not find the program ['msgfmt']

**Comment by brummer10** [comment]
msgfmt is part of gettext. (used for localisation)
You could install gettext or, add the flag ` --disable-nls` to the configure command.

**Comment by brummer10** [comment]
I assume your issue is solved, so close this issue.
