### ISSUE TITLE
err: Package sndfile was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by royi-klein** [brummer10/guitarix#146]
I ran: 
 ./waf configure --prefix=/usr --includeresampler --includeconvolver --optimization

found this error log

**Comment by brummer10** [comment]
Install libsndfile1-dev
In case you run into more missing packages, have a look at the dependency list.
https://github.com/brummer10/guitarix?tab=readme-ov-file#build-dependencies

**Comment by royi-klein** [comment]
I have installed all dependencies but still getting errors:
err: ../test.cpp:1:10: fatal error: fftw3.h: No such file or directory

**Comment by brummer10** [comment]
Ah, okay, 
you need to install  libfftw3-dev

I'll add it to the dependencies list asap.

**Comment by brummer10** [comment]
I assume your issue is solved, so close this issue.
