### ISSUE TITLE
Source not found when running sudo ./waf install

### ISSUE THREAD

**Issue by royi-klein** [brummer10/guitarix#147]
source not found: './resources/back.o' in bld(source=[/home/royi/guitar/guitarix/trunk/src/LV2/xputty/xadjustment.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xadjustment_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xasprintf.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xchildlist.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xchildlist_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xcolor.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xfilepicker.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xpngloader.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xputty.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xwidget-linux.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xwidget-mswin.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xwidget.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/xwidget_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xbutton.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xbutton_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xcombobox.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xcombobox_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xknob.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xknob_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlabel.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlabel_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlistbox.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlistbox_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlistview.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xlistview_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xmenu.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xmenu_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xmeter.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xmeter_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xplayhead.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xplayhead_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xslider.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xslider_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xtooltip.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xtooltip_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xtuner.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xtuner_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xvaluedisplay.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/widgets/xvaluedisplay_private.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/dialogs/xfile-dialog.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/dialogs/xmessage-dialog.cpp, /home/royi/guitar/guitarix/trunk/src/LV2/xputty/dialogs/xmidi_keyboard.cpp, './resources/back.o', './resources/champ.o', './resources/choice.o', './resources/chump.o', './resources/chumpknob.o', './resources/close.o', './resources/directory.o', './resources/directory_open.o', './resources/echocat.o', './resources/echocatknob.o', './resources/echoswitch.o', './resources/error.o', './resources/guitarix.o', './resources/guitarix_dark.o', './resources/guitarix_orange.o', './resources/info.o', './resources/load.o', './resources/message.o', './resources/midikeyboard.o', './resources/play.o', './resources/playreverse.o', './resources/question.o', './resources/record.o', './resources/redeyelogo.o', './resources/screw.o', './resources/screwhead.o', './resources/studiopre.o', './resources/studiopreknob.o', './resources/switch.o', './resources/tape.o', './resources/tapeknob.o', './resources/w20.o', './resources/w20knob.o', './resources/warning.o', './resources/xputty_logo.o'], target='xcairo', meths=['add_ldscript', 'add_mapfile', 'process_rule', 'process_source', 'apply_link', 'add_ldscript_dep', 'process_use', 'propagate_uselib_vars', 'apply_incpaths', 'set_macosx_deployment_target'], features=['cxx', 'cxxstlib'], path=/home/royi/guitar/guitarix/trunk/src/LV2/xputty, idx=1, tg_idx_count=474, _name='xcairo', includes=['.', './header', './header/widgets', './header/dialogs', './resources', './xdgmime'], export_includes=['..'], uselib=['X11', 'CAIRO'], cxxflags='-fPIC', use='re_sources', install_path=None, posted=True, ldflags=[]) in /home/royi/guitar/guitarix/trunk/src/LV2/xputty

**Comment by brummer10** [comment]
This looks like you didn't run `./waf build` before. 
You should follow the build instructions from the main page, best to do a fresh git pull:
https://github.com/brummer10/guitarix?tab=readme-ov-file#building-guitarix-from-source-code

**Comment by royi-klein** [comment]
I did run build, did it again now with a fresh pull. same result

**Comment by brummer10** [comment]
run `./waf distclean` to clean up the sources and build folder before you start with configure/build/install again.

**Comment by Gerhardonius** [comment]
I have the same issue. Persists after redoing it after distclean

**Comment by brummer10** [comment]
Strange. 
Do you use clang/gold or gcc/ld?
what is the output for` ld -v`
what is the output of `gcc -v`
Which distribution do you use?
Maybe it's a race condition in the build script if you've to much cores, in that case you could try to reduce the jobs by add  `--jobs=4` to the configure flags.
If that didn't do the trick and you didn't need the LV2 plugs you could add the `--no-lv2 `flag to configure to skip the build for xputty.

**Comment by Gerhardonius** [comment]
`ld -v` gives GNU ld (GNU Binutils for Ubuntu) 2.34
gcc -v gives bunch of lines, last line is gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 

the --no-lv2 flag did the job. What are the LV2 plugins that I dont have because of using this flag?

**Comment by brummer10** [comment]
> What are the LV2 plugins that I dont have because of using this flag?

Basically all the modules from guitarix as LV2 plugs. In guitarix itself you wont miss anything. 
Most people this day's prefer anyway using the guitarix.vst wrapper instead the LV2 modules when they want to use guitarix in there DAW as plugin.

**Comment by Gerhardonius** [comment]
ok. Thx for your help!
