### ISSUE TITLE
Support for multiple NAM units

### ISSUE THREAD

**Issue by mysticfall** [brummer10/guitarix#148]
I wish Guitarix supported using more than one NAM unit in the rack. I found a very good power amp-only model and another preamp model which I'd like to use in tandem, which is currently not possible because Guitarix only supports a single NAM unit in its rack configuration.

**Comment by brummer10** [comment]
You may check some of the AIDA-X models for the RTNeural module:
https://cloud.aida-x.cc/all

maybe they suit your needs.
But maybe I could add a second NAM module later on.

**Comment by mysticfall** [comment]
Oh, I still can't get over how great Guitarix sounds with a power amp-only NAM model I'm using now, even though I had to drive it with the JCM 800 preamp module.

I just felt really curious what kind of magic Guitarix will do if I could also replace the preamp with another NAM model.

If it's something that would take much effort, I'd be happy to keep my current setup until you may find more leisure some day.

Thanks!

**Comment by brummer10** [comment]
Done now. There are now two modules for NAM and two for RTNeural. On top there is now a RTNeural Multi plug which allow to load two models and blend between them. A endless can of fun.

**Comment by mysticfall** [comment]
I just switched to the `guitarix-git` AUR package to test it, and I'm already having a lot of fun! Who would've thought hooking up the EVH 5150's preamp section into a JMP's poweramp to sound that good. :)

Thanks much! I think you just upgraded Guitarix to a whole different level, where we can not only mimic the tone of well-known amplifiers but also mix and match them to create unique sounds as well.

**Comment by brummer10** [comment]
Nice to hear you like it, so I could close this issue.
