### ISSUE TITLE
build system: LTO detection fails if -flto=auto or similar is used

### ISSUE THREAD

**Issue by Tatsh** [brummer10/guitarix#149]
Your LTO detection doesn't account for when `-flto=auto`, `-flto=N`, etc are used. The arguments are beneficial to tweak LTO processing.

https://github.com/brummer10/guitarix/blob/master/trunk/waftools/cpu_optimization.py#L171-L173

Instead of this check you could use `if any(x.startswith('-flto') for x in cxxflags):`.

https://bugs.gentoo.org/926429

**Comment by brummer10** [comment]
Thanks for the pointer. I've pushed the fix to the repository.

**Comment by Tatsh** [comment]
Thanks!
