### ISSUE TITLE
Is it possible to select a preset via program step?

### ISSUE THREAD

**Issue by dmgeurts** [brummer10/guitarix#150]
I thought this was how I had set things up, but alas it's been a while. As opposed to a normal control switch?

The reason for asking is for pedals which have control change buttons (up/down) and a display showing the selected preset number. This would allow these displays to reliably display the matching preset. Reconfiguring the midi signal sent to a CC would break this link.

**Comment by brummer10** [comment]
Maybe you could use qmidiroute to do that.

**Comment by dmgeurts** [comment]
Selecting presets via their order number directly via prg change ID of the selected program is currently not possible as Guitarix doesn't recognise these signals, but it does send out the number of the selected preset via MIDI out when a preset is selected/changed. Which makes me wonder why it's not using received program IDs as preset selection.

**Comment by brummer10** [comment]
I didn't really understand what you mean. Guitarix using MSB/LSB messages to set the preset. 
![Peek 2024-03-17 05-04](https://github.com/brummer10/guitarix/assets/2683982/de8427f1-8a49-4d39-9c27-0862f2bf7ec1)

**Comment by dmgeurts** [comment]
Thank you, I'll have to have another go at figuring out why this stopped working for me.
