### ISSUE TITLE
eigen isn't found: fatal error: 'Eigen/Dense' file not found

### ISSUE THREAD

**Issue by yurivict** [brummer10/guitarix#153]
```
In file included from ../src/NAM/NeuralAmpModelerCore/NAM/convnet.cpp:10:
../src/NAM/NeuralAmpModelerCore/NAM/dsp.h:10:10: fatal error: 'Eigen/Dense' file not found
   10 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
1 error generated.

c++: warning: optimization flag '-fno-fat-lto-objects' is not supported [-Wignored-optimization-argument]
In file included from ../src/NAM/NeuralAmpModelerCore/NAM/get_dsp.cpp:6:
../src/NAM/NeuralAmpModelerCore/NAM/dsp.h:10:10: fatal error: 'Eigen/Dense' file not found
   10 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
1 error generated.
```

The file in question is present /usr/local/include/eigen3/Eigen/Dense, and pkg-config finds it:
```
$ pkg-config --cflags eigen3
-I/usr/local/include/eigen3
```

Version: 0.45.0

**Comment by brummer10** [comment]
Please try the latest revision from the repository, I've implemented some fixes in the build scripts for using clang.

**Comment by yurivict** [comment]
The latest revision still can't find eigen:
```
In file included from ../src/NAM/NeuralAmpModelerCore/NAM/util.cpp:4:
../src/NAM/NeuralAmpModelerCore/NAM/util.h:6:10: fatal error: 'Eigen/Dense' file not found
    6 | #include <Eigen/Dense> // Eigen::MatrixXf
      |          ^~~~~~~~~~~~~
1 error generated.
```

**Comment by brummer10** [comment]
Strange thing is that Eigen is included in the source as submodule. 
Ensure you've run `git submodule update --init --recursive`
Could you try to remove the lines 34 - 36 from the wscript for NAM:
https://github.com/brummer10/guitarix/blob/master/trunk/src/NAM/wscript#L34

It may be a issue that clang on BSD comes as c++ while the guitarix build system expect CXX. 
Maybe you could try the build flag --check-cxx-compiler=clang++
that should set the CXX flag to clang++
