### ISSUE TITLE
How to install faust debian 12 aarch64

### ISSUE THREAD

**Issue by eloebo** [brummer10/guitarix#155]
Hi I want to compile this for an Rock 4 SE.
Faust is a missing dependancy. The faust version given by pip install faust is to low and a compilation error is given (faust option -s unknown)

Also gettext and pkg-tool was need to be installed but not listed as dependancies

**Comment by brummer10** [comment]
Hi
You don't need faust, `--no-faust`   don't use faust, use the pre-built files in faust-generated
and you don't need gettext `--disable-nls`   Disable native language support

pkg-config, truly is a build dependency which nearly any project expect to be installed when build to check if the build environment suits the needs..

let me know if you success with your attempt.

**Comment by eloebo** [comment]
Thanks for the fast reply! I will continue this project next week. If successful I will donate.

**Comment by eloebo** [comment]
I have been successful in building with adding --no-faust to configuration. Loading NAM models use 121% CPU on Rock Pi 4 and using RTNeural models about 50-70%

**Comment by brummer10** [comment]
Maybe some optimisation flags could reduce the CPU load a bit. I don't know what's supported on a Rock 4 SE. Most important ones on the x86 architecture been -Ofast and -march=x86-64-v3.
