### ISSUE TITLE
Build fails with waf 2.1 (Arch Linux)

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix#156]
Hi Hermann,

I came back to guitarix after a relatively long break and got a failure building from git:
...
`Incompatible Waf, use 2.0`
...

It turns out that waf is now at 2.1.0 on Arch and there is no easy downgrade path
https://archlinux.org/packages/extra/any/waf/

Is there any easy way to fix the build the build besides a waf downgrade?
If not, I'll dig out and old version, but that is probably something that will need to be fixed for the other distros at some point...

**Comment by brummer10** [comment]
I'll Check If I could Update waf. In the mean time you could use the implemented waf Version from guitarix.
Just use
./waf
Instead
waf

**Comment by Gimmeapill** [comment]
Worked like a charm, thanks!

**Comment by brummer10** [comment]
As far I know arch is the only distribution providing a  distribution waf. 
guitarix use a couple of self crafted waf tools which all needs to be reworked then. That's a huge amount of work.
That said, I'm not against updating waf, but I've not the time to do that.

**Comment by brummer10** [comment]
Okay, turns out it was less work then I expected. I'll push a update soon.
