### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [brummer10/guitarix#157]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO resources](https://github.com/FORARTfe/HyMPS#- ) \ [Effects](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Effects.md#-- ) \ [Guitar](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Guitar.md#--- ) \ [Amp Sims](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Guitar.md#amp-sims-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/brummer10/guitarix)
(badge-generator URL: https://badgen.net/github/license/brummer10/guitarix)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by brummer10** [comment]
It's not as easy as it seems because we must cover multiple different Licenses. See here:
https://github.com/brummer10/guitarix/blob/master/trunk/COPYING

additional some parts been Licensed under the 0BSD

**Comment by forart** [comment]
Hi there,
is possible to insert multiple licenses on a single repository:
https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/

We'll post you an example (that we've already seen... LICENSE.GPL, LICENSE.LGPL and so on if not mistaken) as soon as we track it down: stay tuned.

Thanks in advance.
