### ISSUE TITLE
is there a LV2 version of "WaveSharper" effect?

### ISSUE THREAD

**Issue by checo06** [brummer10/guitarix#160]
I was experimenting with "WaveSharper" effect and i think theres no LV2 version of it. I noticed the code is on the file `faust-generated/distortion2.cc` but couldnt trace to a LV2 effect. Is there a version of it? (or maybe something close?)

**Comment by brummer10** [comment]
No, but here is the faust version of it which could be used to make a LV2 plug by using the faust online IDE or XUiDesigner.
All you need to do is remove the line
`import("guitarix.lib");`

and replace all of `smoothi(0.999)` with `si.smooth(0.999)`

https://github.com/brummer10/guitarix/blob/master/trunk/src/faust/distortion2.dsp

**Comment by checo06** [comment]
i did it as explained and worked really good
thanks!

![image](https://github.com/brummer10/guitarix/assets/20385494/82e79458-fe63-4cbf-97d9-caff3dc23ee2)
