### ISSUE TITLE
Native Wayland support

### ISSUE THREAD

**Issue by RichardFevrier** [brummer10/guitarix#163]
Please consider to add native wayland support instead of relying on xwayland.
Thanks for this great project ❤️

**Comment by brummer10** [comment]
Guitarix using gtk(mm)3, so you just need to set
`GDK_BACKEND=wayland`
in your environment to run it native under wayland.

**Comment by RichardFevrier** [comment]
I get the following error. `Cannot open display:`

**Comment by brummer10** [comment]
![2024-06-29_17-28](https://github.com/brummer10/guitarix/assets/2683982/512c428a-0868-431d-98b3-f5f44ab790b8)

**Comment by RichardFevrier** [comment]
![Screenshot from 2024-06-29 17-56-06](https://github.com/brummer10/guitarix/assets/5154754/85766aaf-f1cb-481d-ba9a-69a18a4ebe33)

**Comment by RichardFevrier** [comment]
My bad i didnt check the default windowing system for this flatpak.
It works perfectly, again sorry for the trouble.
