### ISSUE TITLE
need help to compile

### ISSUE THREAD

**Issue by davincigirl** [brummer10/guitarix#166]
Ich schreibe hier in Deutsch da ich kein Wort Englisch spreche. Ich habe mir kürzlich von Musiclab eine Real Guitar gekauft. Ich nutze Windows 10 und auf dem Hackintosh Catalina. In der Regel mache ich nur Sounddesign und meine DAW benutzt Fairlight eine integrierte DAW in dem kostenlosen Davinci Resolve.

Gibt es jemand da draussen, der mir helfen könnte Guitarix als VST zu kompilieren? Ich würde es gerne als Effekt Plugin in dem VST Host Pluginguru Unify (Windows, MAC) benutzen. Ich wollte eine Libary erstellen. Zudem gibt es ein Problem in Davinci Resolve. Anscheinend verwendet Guitarix eine neuere glib als Blackmagic Davinci Resolve und lässt sich nicht installieren.

Vielen Dank im Voraus. Ich hätte gerne den Maintainer angeschrieben brummer10 aber ich konnte nirgendwo eine gültige Email oder Impressum finden. Es gibt eine ältere Portierung auf Github Guitarix-VST aber dort meldet sich niemand.

Daniela Tocan

**Comment by brummer10** [comment]
Hi
Wenn du Real Guitar gekauft hast, hast du doch guitarix.vst fur windows/macos bereits. 
MusicLab hat doch guitarix.vst3 integriert. Der source code dafür befindet sich hier:
 https://github.com/maximalexanian/guitarix-vst

Ich selber betreue die Linux vst3 version:
https://github.com/brummer10/guitarix.vst

Eigentlich, benutzt guitarix keine "neuartigen" glib Funktionen, es kann aber sein das eine compilierte version (binary) einfach gegen eine neuere glib version compiliert is und deswegen nicht auf deinem Rechner funktioniert. Wenn du Real Guitar gekauft hast, solltest du dich an denn support wenden, Musiclab ist eigentlich sehr zuvorkommend zu seinen usern. 

Sonst hast du die Möglichkeit im repository by maximalexanian (der ist von MusicLab) zu gucken, ob du guitarix.vst selber compilieren kannst. 

guitarix selber, als "Stand alone app", ist ein reines Linux Program und wird es immer bleiben. Die Portierung als vst3 plugin wird natürlich weiter gehen.

Wie auch immer, Fairlight gibt es doch auch für Linux.

**Comment by davincigirl** [comment]
Es ist ja auch nicht direkt ein Bug in Guitarix.
Musiclab war sehr nett und haben mir auf die Sprünge geholfen. Was ich vorhabe ist folgendes: In Davinci Resolve gibt es keine Piano Roll. Da behelfe ich mir mit Musescore und schreibe Noten. In Unify (VST Host) kann ich Midi reinladen. Das Problem in Guitarix von Musiclab liegt darin, dass es für deren Integration verändert wurde. Die Presets wenn man eigene entwickelt können nicht abgespeichert oder geladen werden mit anderen Instrumenten und Plugins. Beim kompilieren von Maxim code bin ich gescheitert. Er meldet sich auf Anfrage nicht. Deswegen die freundliche Anfrage ob das jemand für mich machen könnte.

Bislang habe ich fast 100 Presets eingepflegt, würde aber gerne die kompilierte Version mit weitergeben lauffähig als VST3 unter Windows. / Mac aber auch halt in meiner DAW Fairlight Davinci Resolve Es geht nicht um Standallone. Das erledigt der VST Host (Unify) ja. Siehe Screenshot...
Vielleicht kompiliert mir jemand das Ganze. Wäre nett.

Danke Daniela

![Guitarix- Unify](https://github.com/user-attachments/assets/9058eca4-2845-4816-9f86-dbcfe948615d)


Thank you for your project offer. Unfortunately, we have no time for it. We are busy making new guitar in Real instrument series.

We looked into your issue with Davinci Resolve and found a workaround for you. The problem is Guitarix and Resolve uses different versions of glib — 2.70.5 и 2.68.4.

Workaround:

1. Open folder 'C:\Program Files\Blackmagic Design\DaVinci Resolve\’ , backup original files:

 

                gio-2.0-0.dll

                glib-2.0-0.dll

                gmodule-2.0-0.dll

                gobject-2.0-0.dll

 

2. Open folder 'C:\Program Files\Guitarix\’ , copy (replace) these files to Davinci Resolve folder:

 

                gio-2.0-0.dll

                glib-2.0-0.dll

                gmodule-2.0-0.dll

                gobject-2.0-0.dll

                giomm-2.68-1.dll

                glibmm-2.68-1.dll


We tested this scenario and found Guitarix workable.




> Hi Wenn du Real Guitar gekauft hast, hast du doch guitarix.vst fur windows/macos bereits. MusicLab hat doch guitarix.vst3 integriert. Der source code dafür befindet sich hier: https://github.com/maximalexanian/guitarix-vst
> 
> Ich selber betreue die Linux vst3 version: https://github.com/brummer10/guitarix.vst
> 
> Eigentlich, benutzt guitarix keine "neuartigen" glib Funktionen, es kann aber sein das eine compilierte version (binary) einfach gegen eine neuere glib version compiliert is und deswegen nicht auf deinem Rechner funktioniert. Wenn du Real Guitar gekauft hast, solltest du dich an denn support wenden, Musiclab ist eigentlich sehr zuvorkommend zu seinen usern.
> 
> Sonst hast du die Möglichkeit im repository by maximalexanian (der ist von MusicLab) zu gucken, ob du guitarix.vst selber compilieren kannst.
> 
> guitarix selber, als "Stand alone app", ist ein reines Linux Program und wird es immer bleiben. Die Portierung als vst3 plugin wird natürlich weiter gehen.
> 
> Wie auch immer, Fairlight gibt es doch auch für Linux.

**Comment by brummer10** [comment]
Da bin ich leider der falsche Ansprechpartner. Ich betreue (zur Zeit) nur die Linux Versionen. Es kann sein das ich irgendwann mal einen build für Windows und/oder macos anstoße, aber zur Zeit habe ich andere Interessen.
