### ISSUE TITLE
Low level pops on output when in limiting

### ISSUE THREAD

**Issue by frm-dsp** [brummer10/guitarix#172]
I hear faint pops whenever the limiting bar is present and they seem more common while it is increasing.  It is easier to hear on a clean or chorus sounds with the master output volume fairly high.

I looked through the code and have a theory.  The limiter is a compressor.  The gain scaling is averaged, and is always a little behind due to causality.  It does not catch every individual signal value over 1.0, but has to see enough of them for the gain to adapt.

Adding a clipper of some type, hard of soft, after the compressor as part of the limiter would keep the isolated signal value peaks controlled.  The choice of hard or soft, is probably as matter of taste.

If it matters, I am using ubuntu-studio 24 and pipewire.

**Comment by brummer10** [comment]
good catch. 
As I'm running a bit out of time, maybe you could send a pull request to fix this?

**Comment by frm-dsp** [comment]
Ok, I will give it a shot.  It might take a few days.

Are there any restrictions on using existing functions in the current faust standard libraries that I need to follow?

**Comment by brummer10** [comment]
No restrictions. It should just work and be light in CPU usage.

**Comment by frm-dsp** [comment]
See pull request:  "New limiter for the main amp to fix problem with low level pops #173"

I build with faust version 2.72.14 as it was the latest version supported by waf.  It generated different versions of .cc files from what are on the master branch.  To avoid blowing up the commit, I only added hardlim.dsp, and not any of the associated .cc files.

I should be fairly light on the CPU, but is heavier than the old code.

I tried a simpler approach of just adding a hard clipper to the existing limiter and it didn't fix the problem.  Some combination of this and going back to the old limiter setting (ratio=4, threshold=-6.0) works better but was still missed popping and fizzing occasionally.

The new code is structured to allow a trade between latency and correct behavior on low frequency signal.  See the comments in the code.  That might be useful to proper shredders, and could be made visible to the user, but  I don't personally notice even the current "safe" latency.

**Comment by frm-dsp** [comment]
The pull request "Replaces the compressor in hardlim.dsp with soft clipper. #175" is another attempt at a fix for this problem.  It removes any gain modifications from the amp limiter, turning it into a soft clipper.  There is not additional latency added.

It is leaning into the idea that if the amp is in limiting, the problem should be fixed earlier in the chain.

**Comment by frm-dsp** [comment]
Original issue fix with merge of #175.
