### ISSUE TITLE
System slows down after playing a while

### ISSUE THREAD

**Issue by rm5319** [brummer10/guitarix#176]
After a few minutes of using Guitarix to play some guitar my entire system just lags and slows down a lot. UI's get unresponsive and my cursor even jumps. I have to restart to get rid of it. I have no idea where to even start troubleshooting this issue.
My system is more then powerful enough to run Guitarix.

**Comment by brummer10** [comment]
That is very few information. I could ensure you that isn't the case here. 
Which distribution (version)?
which version of guitarix?
which desktop manager?
which display server?
which audio server?
which CPU
which Graphic Card?

check your processes with htop for example while running guitarix to see were the power goes.

**Comment by rm5319** [comment]
Yeah, sorry. Like I said I really don't where to even start so thanks for the suggestions. 
I am running Fedora 40.
I have version  0.46 of Guitarix.
I am using Gnome with Wayland.
I'm running pipewire. 
I have an Intel Core i5-12400F
I have an AMD RX 6700 XT

**Comment by kprox0** [comment]
Long shot, but your issue may be related to [this](https://forum.manjaro.org/t/high-single-cpu-core-usage-on-wayland-when-using-external-display/162353).

I have experienced high CPU usage with Wayland X11 bridge on Fedora 40 on some PC's.

You may want to try this to see if the Wayland X11 Bridge is the culprit: ```dnf erase xwaylandvideobridge```

Have you tried running Guitarix on an alternative desktop such as Xfce?

**Comment by rm5319** [comment]
I don't have XWaylandVideoBridge installed. I have tried running Guitarix on my laptop which runs the exact same as my pc without luck. I do have Guitarix running under just normal XWayland. I guess I will try running it under native Wayland. Will update later
