### ISSUE TITLE
[Feature request] 41-edo added to tuner

### ISSUE THREAD

**Issue by wolftune** [brummer10/guitarix#18]
As discussed at https://sourceforge.net/p/guitarix/discussion/general/thread/feb6d67e86/

**Comment by wolftune** [comment]
bump, and btw, what a great time to do this while Guitarix is still at version 41!!

**Comment by brummer10** [comment]
Oh, yes, I've forgotten about that, will defiantly do that.

**Comment by wolftune** [comment]
To point more specifically, the details needed are at this comment at that thread:

https://sourceforge.net/p/guitarix/discussion/general/thread/feb6d67e86/#ac12/6342
