### ISSUE TITLE
Segmentation fault when changing buffer size

### ISSUE THREAD

**Issue by edwloef** [brummer10/guitarix#182]
I'm able to easily bring guitarix to segfault by repeatedly switching between very small and very large buffer sizes. However, I still often encounter this when just trying to change from 1024 to 256 samples. Running fully updated Arch with pipewire-jack, occurs on both the Arch package and the current git revision.

Backtrace: [bt.txt](https://github.com/user-attachments/files/17174421/bt.txt)

**Comment by tristantarrant** [comment]
happens to me as well. workaround is to change it via qjackctl

**Comment by brummer10** [comment]
This looks like a issue within pipewire. 
Guitarix send a request to jack to change the buffersize, then it wait for the response. Guitarix then react on the response and change it's internal buffersizes to the size given by jack. That worked flawless with jackd. According to the backtrace, pipewire-jack response with the requested buffersize, but didn't change it to the new size, hence it crash. I remember that this have worked once with pipewire as well, so there must have been something changed to the no good.

**Comment by edwloef** [comment]
Unfortunately I'm not knowledgeable enough about how Jack works to report this to the folks over at Pipewire, is this something you could do?

**Comment by brummer10** [comment]
It doesn't request more then your report here.

**Comment by otuva** [comment]
for the flatpak, I couldn't change from the interface so I'm posting my steps for later reference

```
flatpak run --command=bash org.guitarix.Guitarix
mkdir ~/.var/app/org.guitarix.Guitarix/config/pipewire
cp /usr/share/pipewire/jack.conf ~/.var/app/org.guitarix.Guitarix/config/pipewire/jack.conf
```

then inside the jack conf, I changed below line. made it 128 to remove any delay. 
I guess it should give ~5ms delay now

```
...
jack.properties = {
     node.latency       = 128/48000
     #node.rate          = 1/48000
     #node.quantum       = 1024/48000
     #node.lock-quantum  = true
...
```
