### ISSUE TITLE
scrolling up while holding a one rack module widget with left mouse bug

### ISSUE THREAD

**Issue by noisecode3** [brummer10/guitarix#185]
Hi, I had this problem for a while or maybe its me using the software wrong, but every time I grab a module and just hold it over the other rack modules it starts to scroll up, is it only me or what going on? I think this was really bothering me

**Comment by brummer10** [comment]
That should only happen when you select a Stereo plug, the rack scroll then down to the first possible entry place in the stereo rack. When you select the "split" view, it shouldn't happen at all.

**Comment by noisecode3** [comment]
That was making me think the default view was bugged. I get it now, I think that design was a bit to weird for me. I could suggest just graying out the irrelevant plugins, like stereo plug would gray out mono plug, some more obvious visual feedback could be needed when it starts scrolling like that.

**Comment by noisecode3** [comment]
I also notice the limiter font has the same color as the background, right next to the big Master Volume knob, on the main top amp. Maybe move up the font a bit so it gets to the lime green background

**Comment by brummer10** [comment]
> I also notice the limiter font has the same color as the background,

Which version do you use? With latest githead the label should appear on the lime green background.

> I could suggest just graying out the irrelevant plugins, like stereo plug would gray out mono plug, some more obvious visual feedback could be needed when it starts scrolling like that.

There is the black/orange line which appear as soon the new plug is at a place were it could dropped. 
I'm pretty sure, when you know now about the separation of the mono/stereo rack, you'll get soon used to it without the need to grey out the rest of the rack. True is that guitarix is the only app doing this separation, we does it to reduce the CPU usage.

**Comment by noisecode3** [comment]
I used 0.46.0 from this repo here, last git dont build. When it starts scrolling like that for a new users it could be too confusing and some might get frustrated and quit the application, completely weirded out, but we don't need those users, lol.

**Comment by tristantarrant** [comment]
> > I also notice the limiter font has the same color as the background,
> 
> Which version do you use? With latest githead the label should appear on the lime green background.

It happens here too with latest git 02f6c8373d9055fa01252dff91561ec948903e35

![image](https://github.com/user-attachments/assets/bf1d541a-ee99-4795-a888-3fd1b8066bc9)

**Comment by brummer10** [comment]
Ah, I see,. My fool. when you select "Show values" from the option menu it is aligned. 
I need to investigate.

**Comment by tristantarrant** [comment]
> I also notice the limiter font has the same color as the background, right next to the big Master Volume knob, on the main top amp. Maybe move up the text a bit so it gets to the lime green background. If you want to I can help with some GUI improvements. I can pr, if you don't like it I can just keep the patches for myself. I like this software

@noisecode3 you should have opened a separate issue for this though

**Comment by brummer10** [comment]
> > I also notice the limiter font has the same color as the background, right next to the big Master Volume knob, on the main top amp. Maybe move up the text a bit so it gets to the lime green background. If you want to I can help with some GUI improvements. I can pr, if you don't like it I can just keep the patches for myself. I like this software
> 
> @noisecode3 you should have opened a separate issue for this though

Indeed, I've overseen this part here. Yes, patches been welcome.

**Comment by noisecode3** [comment]
Okej, but Im closing this one cus, it is not a problem

**Comment by brummer10** [comment]
@tristantarrant 
I've pushed a Fix for the limiter label issue to the repository.
