### ISSUE TITLE
Json parser fails while downloading online presets

### ISSUE THREAD

**Issue by zainin** [brummer10/guitarix#186]
When trying to fetch the list of online presets from musical-artifacts it fails without any obvious errors in the GUI.  
Instead, you are left with a blank list.

In console the following is logged:
```
I [15:00:41]  download_file  ***  https://musical-artifacts.com/artifacts.json?apps=guitarix
JsonException: Json parse error: bad token: 'n'
```

**Comment by brummer10** [comment]
Hi
Thanks for the pointer and the pull request. That points me in the right direction. 
Latest commit should fix the issue.

regards
hermann
