### ISSUE TITLE
Missing faust in list of build dependencies.

### ISSUE THREAD

**Issue by rerdavies** [brummer10/guitarix#188]
Faust is missing from the list of build dependencies in README.md.

I am building guitarix on Raspberry Pi Os 

    Linux raspberrypi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

Running 

    ./waf configure --prefix=/usr --includeresampler --includeconvolver --optimization

produces the following error:

     Could not find the program ['faust']
     (complete log in ....trunk/build/config.log)

Running 

    sudo apt install faust 

corrects the problem.

**Comment by brummer10** [comment]
faust isn't strictly needed to build guitarix. You could disable it with the `-no-faust` configure flag. 
Al files comes prebuild in the source. 
But, there seems to be a bug in the waf script, as it shouldn't error out when no faust is found. I need to check this.

**Comment by brummer10** [comment]
Okay, this is fixed now in latest git. Now, the configure step proceed and you could build guitarix without faust.
