### ISSUE TITLE
Dark text on Neural Amp Modeler almost impossible to read on most skins.

### ISSUE THREAD

**Issue by Dark-Thoughts** [brummer10/guitarix#189]
Unlike other text, the loaded file name text remains black when, for example, choosing one of the dark or very busy skins. I also feel it should look a little more like a little display, rather than an engraving or imprint on the surface.

![image](https://github.com/user-attachments/assets/61aecf31-3030-493f-a997-baac9b56f11a)

**Comment by brummer10** [comment]
Yep, my fool. 
Thanks for reporting the issue, I'll investigate.

**Comment by brummer10** [comment]
Should be fixed with the latest commit.
