### ISSUE TITLE
[Request] Add cycle widget to NAM and RTNeural modules

### ISSUE THREAD

**Issue by pramuko** [brummer10/guitarix#192]
Currently, NAM and RTNeural modules allow the user to open a file dialog and choose a model. After that, the module displays the name of the loaded model on the GUI.

![NAM-GUI-improvement-before](https://github.com/user-attachments/assets/e52b4b8f-a90d-4752-9d37-5240e9d73cab)

This works fine. However, trying another model requires a few clicks, just like above. This workflow might be streamlined if the module makes use of cycle/dropdown widget just like the cabinet module. The NAM module would list all *.nam files in the same directory and display them using the dropdown widget.

![NAM-GUI-improvement-after](https://github.com/user-attachments/assets/341032ff-73b6-4777-afe8-c57dd6649d4d)

That way, the user only needs to navigate using the file picker dialog once. After that, he only needs to cycle through the files in the same folder using the widget.

**Comment by brummer10** [comment]
Yep. It may take some time before I could do that, but it is defiantly planed. (patches been welcome)

**Comment by brummer10** [comment]
Done,

**Comment by brummer10** [comment]
https://i.imgur.com/Cpehb1H.gif
