### ISSUE TITLE
Nsm, can't hide gui in wayland

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/guitarix#198]
`Guitarix version 0.46.0`
Works in X11, not in wayland

Gui can be shown, but not be hidden. 

I see a few messages
```
Gdk-Message: 14:37:35.980: Window 0x61ed30c17060 is a temporary window without parent, application will not be able to position it on screen.

(guitarix:32447): Gtk-CRITICAL **: 14:37:36.182: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by brummer10** [comment]
Same here, wayland didn't work on my machine at all, not even in a virtual box. So I expect the issue is in wayland

**Comment by grammoboy2** [comment]
It seems to work in river WM.
