### ISSUE TITLE
gx_colwah.lv2 manifest.ttl is installed in wrong location

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/guitarix#2]
The `manifest.ttl` file for the gx_colwah.lv2 LV2 bundle is installed as `/usr/lib/lv2/gx_wah.lv2/manifest.ttl`, but the bundle is actually in `/usr/lib/lv2/gx_colwah.lv2`. The source directory is called `src/LV2/gx_wah.lv2`, though, apparently the `wscript` doesn't handle that correctly.

Encountered in guitarix 0.39.0.

**Comment by brummer10** [comment]
Yes, I noticed that to late, it's fixed in the repository, but was to late for the release.

**Comment by brummer10** [comment]
This is fixed with the latest release.
