### ISSUE TITLE
Cannot select non-user's preset.

### ISSUE THREAD

**Issue by KottV** [brummer10/guitarix#21]
Greetings!

I found that with 0.41.0 it's impossible to select preset from factory or from inet, they looks like inactive and haven't numbers. Mouse clicking does nothing too:

![изображение](https://user-images.githubusercontent.com/4686351/94983914-1328d180-058a-11eb-8168-35ee32bb6ed3.png)

do I miss something?

**Comment by brummer10** [comment]
Strange, you may try to backup your guitarix config folder and start from scratch. 
The numbers for the presets appear as soon a preset from a bank is selected, they are in relation to the active bank
Guitarix config is written to ~/.config/guitarix, rename this folder to guitarix~old for example and let guitarix create a new one. 
If that does the trick, you could import your presets by drag'n'drop the preset banks from the file manager into the guitarix preset window.

**Comment by KottV** [comment]
I've tried that with no result.
Strange that 0.39 works fine, moreover after upgrade to 0.41 some patches became available. Gonna try to find the difference.

**Comment by brummer10** [comment]
do you get any log in the Log window?

**Comment by KottV** [comment]
no...

in strace i found these lines, but it unlikely relevant:
```stat("/usr/local/share/gx_head/factorysettings/Sonnie_Tele.gx", {st_mode=S_IFREG|0664, st_size=213897, ...}) = 0
lseek(13, 0, SEEK_CUR)                  = 124
close(13)                               = 0
openat(AT_FDCWD, "/home/kv/.config/guitarix/pluginpresets/lv2/seq", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/kv/.config/guitarix/pluginpresets/seq", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/share/gx_head/factorysettings/seq", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by brummer10** [comment]
I mean when you click on the little icon on the right bottom. It open a log window. Now, when you try to load a preset, comes there any message in the log window? Also, do the presets appear in the preset menu on top? 

Further more, which distribution you are on and were do you get guitarix from?  Do you build it yourself or is it a distributed package?

**Comment by KottV** [comment]
No, nothing when I click on factory preset and nothing at the top of window. A can select factory bank by letter, then it waits for preset and as there is no any number in presets it returns to scratchpad.
Only works when I select user's preset with number by keyboard, mouse doesn't work too:
````
[19:30:33]  loaded state  ***  from file /home/kv/.config/guitarix/gx_head_rc
[19:30:34]  Jack init  ***  The jack sample rate is 48000/sec
[19:30:34]  Jack init  ***  The jack buffer size is 128/frames ... 
[19:30:45]  loaded preset  ***  654 from file /home/kv/.config/guitarix/banks/scratchpad.gx
[19:30:47]  loaded preset  ***  livebuffer1 from file /home/kv/.config/guitarix/banks/scratchpad.gx
[19:30:50]  loaded preset  ***  654 from file /home/kv/.config/guitarix/banks/scratchpad.gx
```

I've build guitarix by self on openSUSE Tumbleweed. I'm gonna check on Ubuntu in VM a bit later.

**Comment by brummer10** [comment]
I just noticed on the screenshot, there is something wired. The bank B: HarryVH and B: brummer
B: brummer should be C: brummer. 
So it looks like the bank counting (banks are count by letters, preset been counted by numbers) is corrupted somehow. 
That gives me the impression as if either the source code you've build from is corrupted or during installation something gets wrong. 
When you update from 0.39.x do you've deinstalled the old version? Sometimes installations of different versions, maybe in /usr and /usr/local leads to very wired beehive. 

What happen when you point your mouse above the preset window and press "c" and then " 0" on the keyboard?
And what happen when you press "b" and then "0"?

**Comment by KottV** [comment]
>>I just noticed on the screenshot, there is something wired. The bank B: HarryVH and B: brummer
B: brummer should be C: brummer.

I made this mess by copying factory preset into home dir. After cleaning all is like you said.

>>What happen when you point your mouse above the preset window and press "c" and then " 0" on the keyboard?
And what happen when you press "b" and then "0"?

![изображение](https://user-images.githubusercontent.com/4686351/94990294-543ad900-05be-11eb-82f0-5c6ca56c6f58.png)


It works!
But, as i remember presets can be switched with mouse, no? And after I switch to other bank or restart guitarix the presets became without numbers again, is that right?

**Comment by brummer10** [comment]
> And after I switch to other bank or restart guitarix the presets became without numbers again, is that right?

Yes, that is right. Only presets in the active bank have numbers. So you could switch preset by just press a number. Switch bank by press the letter of the bank and select preset by press the number.

> But, as i remember presets can be switched with mouse, no? 
Yes, preset switching by mouse should work as well. 
I've no idea why it didn't work for you. Which desktop manager is it? All other mouse actions in the guitarix interface works as expected? 
I've checked the gtk3 version for Tumbleweed and it's the same then mine on debian/sid, so that couldn't be the issue.

**Comment by KottV** [comment]
It's KDE (Plasma). All other actions works.
I can select bank with mouse. When I click on preset it changes the color but doesn't load.

See the selected _0: Solo Lead_ and loaded **3: Distortion Lead**:

![изображение](https://user-images.githubusercontent.com/4686351/94990926-d927f180-05c2-11eb-95ed-4260bfae3cba.png)

**Comment by KottV** [comment]
Should it work with navigation keys and enter? It looks the same, I can choose the bank with arrow keys, switch to presets column with tab and navigate thru presets, but pressing enter just closes preset sectkion.

**Comment by brummer10** [comment]
> Should it work with navigation keys and enter? 
No, that isn't implemented. 
Still, it's strange that selection with mouse button press didn't work for you. 
I may do a KDE test installation to check out what goes wrong.

**Comment by KottV** [comment]
I understand. Thank you :)

**Comment by brummer10** [comment]
Okay, I do a test install of openSUSE Tumbleweed and could reproduce the issue. 
So I was able to push a fix for it to our repository. 
Thanks for reporting the issue. Let us know please if that fixed the issue for you as well.

**Comment by KottV** [comment]
Confirm that issue is fixed. Thanks again!
