### ISSUE TITLE
Option to turn High Pass filter off

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#22]
I saw a discussion over at LinuxMusicians about Guitarix, and Hermann mentioned some high and low pass filters that are always on for the sake of smoother distorted sounds. As I play Bass, I really don't use much distortion but I do notice that my old tube amp has much deeper bottom end than almost all digital simulations, including Guitarix. 

Would it be possible to have an option to turn the high pass filter off, so that I can get a tone closer to my old Bassman without having to turn up the Bass Boost? The Bass boost works, but has the "boomy" sound of an EQ, not the tight deepness I get from my old amp. If you know what I mean.

I could try doing my own "alpha" test of this if you would tell me where in the code the high pass filter is. I could  compile with it commented out and let you know whether I experience any problems or if it sounds good or not.

Thanks
-Ted

**Comment by brummer10** [comment]
Hi @Rippert 
Okay, you find the high pass in /src/faust/guitarix.lib line 97 
It is set to 31Hz. To remove it edit line 91 and remove 
` : hpf`
You need faust 2.20.2 to rebuild from faust source.

regards
hermann

**Comment by Rippert** [comment]
OK. Thanks Hermann. 

I assume I could also just change the 31.0 to something like 20.0 to see what happens. 

I'll have to build faust 2.20.2 from source as it's not available on my distribution. I'll let you know if anything comes of this if I can get it working.

**Comment by brummer10** [comment]
> I assume I could also just change the 31.0 to something like 20.0 to see what happens.

Yes, sure.

**Comment by Rippert** [comment]
OK. Did it. it works fine without the highpass filter, and I like the sound much more for my Bass. I just eliminated the `: hpf` code like you suggested. I haven't tried playing with the filter frequency.

I'm doing A/B testing right now using another computer with the old code. I'd like to A/B test on the same hardware to make sure that the difference is all from the code change. I'll work on a kludge for that.

How hard would it be to add a button, or just some additional tube options in the current list? I really only use the 12ax7, 6DJ8 and the master 6V6 versions of those two right now, but I may start using some others now that I've made this change.

Also, I notice that the code for the Push Pull 6V6 options all have a speaker cab type bandpass filter with a lower cutoff of 310 Hz? That seems very high. I'm going to try just removing that tomorrow. Is there some danger in doing so?

**Comment by brummer10** [comment]
Nice.
I'll think about it, maybe I just remove the hpf completely. 
I can't really remember why I've introduced it at all, I did a short check here, and found it wouldn't hurt to remove it (opposite is the true) .
Maybe better then implement a other option were noon knows what it is.  

Same goes for the speakerdb(), you could remove it without any danger, let me know your finds and I'm open to remove it.

**Comment by Rippert** [comment]
I removed the `speakerbp` from all the internal tube dsp files for push pull setups. Huge difference. They've gone from useless to great for my Bass settings. Lots of full, tight, bottom end and I can actually hear the differences between the various preamp tubes.

The only reason I could see to keep the old 31 Hz highpass filter or the `speakerbp` stuff is so that users with old presets don't complain. I would never use the old options myself at this point. Seems like the old sounds should be easily recreated with just a L/H Filter plugin in front of the tube section. Maybe make the changes and add a note in the release that explains this?

You also might look at removing the `speakerbp` stuff from the LV2 plugins, if you're going to do this.

**Comment by brummer10** [comment]
Okay, I'll going to remove this filters from the tubes.

**Comment by brummer10** [comment]
So, done.
Thanks for testing it out and help to make guitarix better.

**Comment by Rippert** [comment]
I tried out the latest commit, and it seems to work perfectly.

Thanks again
