### ISSUE TITLE
Add input and output volume (gain) controls to Power Amp plugin

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#23]
I was experimenting with the Power Amp plugin and realized that I needed to use a volume plugin both before and after it to control the distortion level and the output level. I imagine this would also be useful for other plugins.

Is there a way to have more than a single instance of a plugin in the Rack? 

It seems like putting the plugin into the rack from the pool removes it from the pool so you can only have one instance of each.

**Comment by brummer10** [comment]
It's not possible in guitarix to have multiple instances of the same plugin. (We use preload to ensure a fast preset switching, that will contradict with multiple instances of the same shared object). 
However, I could implement volume controls in the poweramp plugin to have better control above the distortion level.

**Comment by Rippert** [comment]
OK. I thought that might be the case. I've changed the title of issue to reflect your suggestion. The input and output gain controls should make the Power Amp more versatile. 

I tried to look at the Power Amp Faust code, but it seems to be different than the other tube simulations. More like a whole amp sim, at least from the names of the modules, like Champ for the 6V6GT. Is there a way to set the input levels at  the Faust module level so they are not quite so disparate (some pretty linear while others are completely saturated at the same input level to the plugin)?

**Comment by brummer10** [comment]
Okay, done.
Power Amp's now have  In/Output volume controls 

> I tried to look at the Power Amp Faust code, but it seems to be different than the other tube simulations. 

Yes, they been build with the dkbuilder

**Comment by Rippert** [comment]
Nice. Thanks. 

I'll have to look at dkbuilder. Never really noticed it before. There really are a lot of hidden gems in Guitarix.

**Comment by Rippert** [comment]
I've played with the Power Amp plugin some more, and the in/out volumes knobs work fine. So I'll close this issue. You might think about looking at all the other non-linear plugins, and making sure they have an input and output gain control. I was also testing out the Multi Band Distortion, and had to add a volume plugin before it. It does have a gain on the output. Maybe too much work to change every one that's missing either in or out volume, but it's a thought.

Thanks again
