### ISSUE TITLE
Lv2 plugin gx_zita_rev1 "LEVEL" port has invalid min/max

### ISSUE THREAD

**Issue by JohannesLorenz** [brummer10/guitarix#24]
The port is logarithmic. From [the Lv2 specs](http://lv2plug.in/ns/ext/port-props#logarithmic): "The lower and upper bounds must be specified, and must be of the same sign.". The ttl has min < 0 < max:

https://github.com/brummer10/guitarix/blob/5fb7e25d5ea276b988d504b7368a2aeea3baccb9/trunk/src/LV2/gx_zita_rev1.lv2/gx_zita_rev1.ttl#L64-L69

**Comment by brummer10** [comment]
Good catch.
It means that I need to remove the logarithmic hint from the ttl for this port. 
To bad, as it has to be logarithmic. Anyway it only affect the host provided UI, as logarithmic is handled in the Plugin GUI internal.

**Comment by brummer10** [comment]
A fix is pushed to the repository

**Comment by JohannesLorenz** [comment]
Alternatively, you could have added an offset to min/max, like `[-60,4]` -> `[-64, -0.001]` (and subtract the offset internally)

**Comment by brummer10** [comment]
Yes, sure, just change the range of the control in the ttl may infect existing sessions, were the removal of the logarithmic hint just change the feel of the internal controller from the host.

**Comment by JohannesLorenz** [comment]
Anyways, thanks for the fix!
