### ISSUE TITLE
Python version for dkbuilder

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#28]
I have an issue with the dependencies listed to run dkbuilder. My distribution has a conflict between the packages `virtualenv` and `python-virtualenv`. The former is python3 and it explicitly breaks the latter which is python2. Since `virtualenv` is a meta-package, I think I can just install the other listed dependencies to get a python2 setup or use the versions prefaced with `python3-` to get a python3 setup.

Should I install the python3 versions of all dependencies or the python2 versions?

_Certainly not your fault, but this is one of the things I hate about Python._

**Comment by brummer10** [comment]
Dkbuilder only work with python2. 
Just leave out the virtualenv when it is only python3.

**Comment by Rippert** [comment]
OK. Thank You.
