### ISSUE TITLE
NSM support

### ISSUE THREAD

**Issue by grammoboy2** [brummer10/guitarix#3]
As one of the pillars of modular linuxaudio it's time for NSM (Non-Session-Manager) support in Guitarix.

NSM is now chosen by the main developer of JACK as session management API to use and jack-session is set to deprecated: https://media.ccc.de/v/sonoj2019-1902-jack-past-present-future#t=1873

There are about 30 applications supporting NSM at the moment. 

A great feature of NSM is the fact that it stores all files of the different JACK applications in one session folder. This makes it extremely easy to share sessions between musicians and guitarists.

http://non.tuxfamily.org/wiki/Non%20Session%20Manager
non.tuxfamily.org/nsm/API.html

**Comment by brummer10** [comment]
NSM support is now in git.

**Comment by simonvanderveldt** [comment]
@brummer10 :+1: 

Looking at the commit (https://github.com/brummer10/guitarix/commit/f6b1ab4c723480a090c38ca3eb68c5da57da885b#diff-f7e2ab7c4f52df291e52f1428363a2c3R322) for the standalone build NSM/liblo support isn't optional.
Is this correct? Do you have plans to make this optional or not?

**Comment by brummer10** [comment]
Yes, good catch. I've made it now optional. (Default true)
