### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by lattice0** [brummer10/guitarix#35]
Hello, this project is very interesting. It looks huge. I tried to take a look at the code and it looks very related to GDK. 

Although Jack maybe could work on Android since it's Linux (don't know exactly), I think it's not that easy. It looks like the engine.h file: https://github.com/brummer10/guitarix/blob/master/trunk/src/headers/engine.h has some dependencies to LV2 and jack. Maybe it's possible to port some of the sound processing functions to work with raw wav data, without using microphone from Jack? On Android, Oboe is a library that is able to open microphones and receive the .wav stream.

Thanks!

**Comment by atsushieno** [comment]
I actually have Guitarix ported to my own audio plugin framework. https://github.com/atsushieno/aap-lv2-guitarix which is almost working for static audio processing. LV2 and JUCE are kind of supported. Oboe is not involved as plugins don't really need access to platform audio.

There is no rack, no dedicated UI, no useful host app beyond my dogfooding static generator example.
