### ISSUE TITLE
Support sample rates above 96 kHz

### ISSUE THREAD

**Issue by psrcek** [brummer10/guitarix#4]
My audio interface natively supports 192 KHz playback, so I set jack to use that. Guitarix won't launch and this message is displayed:

![image](https://user-images.githubusercontent.com/13370323/78710507-bc617880-7915-11ea-9a52-9c674e6e3ada.png)

This seems like an arbitrary software limitation that is completely pointless. Jack supports refresh rates above 96 KHz just fine.

**Comment by psrcek** [comment]
Actually, yeah, it is completely arbitrary. https://github.com/brummer10/guitarix/blob/2addb8b8028486992b1ca93f4a6c000d39cb0911/trunk/src/gx_head/engine/gx_jack.cpp#L392
Why would you do that????

**Comment by brummer10** [comment]
Because we use iir filters which didn't work well with 192 KHz. Also the convolvers becomes trouble with higher sample rates then 96 kHz. 
You could try it out by comment out the part you mention.

**Comment by psrcek** [comment]
I tried compiling this myself and I just got a lot of errors. (see image below)
Guitarix attaches to jack just fine, and I can use the last preset that I used, but upon switching presets it crashes with a segmentation fault. The regular guitarix package works fine.

![image](https://user-images.githubusercontent.com/13370323/78834534-02d6d600-79ef-11ea-9560-040a31571020.png)

To compile I used [this](https://aur.archlinux.org/packages/guitarix-git/) arch linux AUR repo.
I just added the following prepare function and patch.

```
prepare() {
    cd "${pkgname%-*}"
    patch --forward --strip=1 --input="${srcdir}/sample_rate_unlock.patch"
}
```
https://gist.github.com/psrcek/e197017d68dd1f948b17f788c933ff23

**Comment by brummer10** [comment]
Well, that's what I said. Sample rates above 96 kHz didn't been supported. 
Hence we put in the warning message, it isn't arbitrary.
Internal guitarix use a fixed sample rate of 96 kHz for most of it filters/effects, supporting higher sample rates will require downsampling to match the filter coefficients.
