### ISSUE TITLE
version 0.42.0 - About dialog box has wrong version number

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#43]
Just tried version 0.42.0. Overall very good, but did notice that the dialog box that opens when the `About `menus is clicked lists the version number as `0.41.0`. I did check the git log, and I am using 0.42.0.

**Comment by hfiguiere** [comment]
FWIW: I just built it (from the tarball) and it show the right version.

**Comment by Rippert** [comment]
Ok. I just did an incremental build. I'll try a full rebuild when I get a
chance.

**Comment by brummer10** [comment]
The version is set in the wscript, so, yes, to get the version right you must at least run ./waf configure so that the new version is written to config.h

**Comment by Rippert** [comment]
OK. A new `./waf configure` fixed it.
