### ISSUE TITLE
Increase range of Power Amp Input and Output controls (version 0.42.0)

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#44]
On version 0.42.0, it is possible to saturate the PowerAmp tubes, especially the singlended 6V6, with the Input Volume knob all the way down at -20dB. This is with the overall signal level well below clipping when the  PowerAmp section is turned off (actually everything turned off but the main tube amp section).

A range of -30dB to +30dB may be more useful than the current -20dB to +20B. Probably want to also increase the Output gain range also, to match if you do this.

This allows setting the Pre Gain and Master Gain of the Tube section how one likes it and then tweaking the PowerAmp to get just the right tone.

This is also more consistent with the hardware PowerAmps I own that have a gain range of around 30dB.

**Comment by brummer10** [comment]
Good hint. Yes, I'll do that.

**Comment by brummer10** [comment]
done

**Comment by Rippert** [comment]
Works well, thanks.
