### ISSUE TITLE
Bug: compile error (faust)

### ISSUE THREAD

**Issue by buscon** [brummer10/guitarix#46]
I am getting the following compile error on version 0.42.1:

$ ./waf build -v
Waf: Entering directory `/home/marcello/Documents/Softwares/guitarix-0.42.1/build'
[ 92/309] Compiling src/faust/compressor.dsp
11:36:05 runner system command -> /home/marcello/Documents/Softwares/guitarix-0.42.1/tools/dsp2cc -o /home/marcello/Documents/Softwares/guitarix-0.42.1/build/src/faust/compressor.cc --no-version-header --double --init-type=plugin-instance ../src/faust/compressor.dsp
11:36:05 runner ['/home/marcello/Documents/Softwares/guitarix-0.42.1/tools/dsp2cc', '-o', '/home/marcello/Documents/Softwares/guitarix-0.42.1/build/src/faust/compressor.cc', '--no-version-header', '--double', '--init-type=plugin-instance', '../src/faust/compressor.dsp']
Alarm clock
Traceback (most recent call last):
  File "/home/marcello/Documents/Softwares/guitarix-0.42.1/tools/dsp2cc", line 2337, in <module>
    main()
  File "/home/marcello/Documents/Softwares/guitarix-0.42.1/tools/dsp2cc", line 2315, in main
    parser = Parser(faust.stdout,
  File "/home/marcello/Documents/Softwares/guitarix-0.42.1/tools/dsp2cc", line 563, in __init__
    self.faust_version = headvers.group(3)
AttributeError: 'NoneType' object has no attribute 'group'

Waf: Leaving directory `/home/marcello/Documents/Softwares/guitarix-0.42.1/build'
Build failed
 -> task in '' failed with exit status 1: 
	{task 139708088173168: dsp compressor.dsp -> compressor.cc}

**Comment by brummer10** [comment]
you should configure with `--no-faust` flag 
all sources comes pre-build, so no need to rebuild them from faust level. 
btw. which version of faust do you using?

**Comment by buscon** [comment]
> you should configure with `--no-faust` flag
> all sources comes pre-build, so no need to rebuild them from faust level.

ok, that seems to make it work.
one comment about that: I was compiling 0.42.0 with faust and I did not get this error.

> btw. which version of faust do you using?

it is:
2.20.2~ds0-1
on Linux Mint.

**Comment by brummer10** [comment]
Okay, seems I need to remove 2.20.2 from the accepted faust versions. 
btw. the error seems to be introduced by rd.maxn(), last versions I use rd.mean(), but, I only do that because rd.maxn() was broken for some time in faust. As soon it orks again, I switched back to use it. Faust version is 2.27.2.
What I've forgotten is to remove 2.20.2 from the accepted versions, otherwise you wouldn't run into this issue, as build from faust source would be disabled for 2.20.2. So thanks for reporting it, I'll investigate.
regards
hermann

**Comment by buscon** [comment]
thank you for the explanation and for the great work!

**Comment by natestokes** [comment]
I hit this problem too.  Downloaded the source today, but the nofaust workaround worked fine.

**Comment by hfiguiere** [comment]
It also fails with 2.15.11
```
[hub@rocinante]~/source/guitarix-git/trunk% ./waf build -v
Waf: Entering directory `/home/hub/source/guitarix-git/trunk/build'
[171/243] Compiling src/faust/compressor.dsp
14:33:07 runner system command -> /home/hub/source/guitarix-git/trunk/tools/dsp2cc -o /home/hub/source/guitarix-git/trunk/build/src/faust/compressor.cc --no-version-header --double --init-type=plugin-instance ../src/faust/compressor.dsp
14:33:07 runner ['/home/hub/source/guitarix-git/trunk/tools/dsp2cc', '-o', '/home/hub/source/guitarix-git/trunk/build/src/faust/compressor.cc', '--no-version-header', '--double', '--init-type=plugin-instance', '../src/faust/compressor.dsp']
Traceback (most recent call last):
  File "/home/hub/source/guitarix-git/trunk/tools/dsp2cc", line 2337, in <module>
    main()
  File "/home/hub/source/guitarix-git/trunk/tools/dsp2cc", line 2315, in main
    parser = Parser(faust.stdout,
  File "/home/hub/source/guitarix-git/trunk/tools/dsp2cc", line 563, in __init__
    self.faust_version = headvers.group(3)
AttributeError: 'NoneType' object has no attribute 'group'

Waf: Leaving directory `/home/hub/source/guitarix-git/trunk/build'
Build failed
 -> task in '' failed with exit status 1: 
	{task 139970940121152: dsp compressor.dsp -> compressor.cc}
''
[hub@rocinante]~/source/guitarix-git/trunk% faust --version
FAUST Version 2.15.11
```

(I'll upgrade to 2.27.2 in a bit)
