### ISSUE TITLE
Question: New dependencies since 0.40.x Cairo/xlib?

### ISSUE THREAD

**Issue by webaake** [brummer10/guitarix#51]
SORRY! The dev on Reaper Linux is just way too fast! There's a new version every day. So today, in Reaper 6.21+dev0130 Gx GUIS:s are there again!!

Sorry to bother you!

Just a question about possible new deps when compiling LV2 since version 0.40.x . I just compiled 0.42.x (latest) and get no LV2 GUI. In the Readme files I read that since version 0.40 Gx uses cairo/xlib instead of GTK for Lv2 plugins, but I see no new deps for that? I'm a just way off (or stupid)?

There are a few possible sources for the "no gui" problem; I'm using the newest dev version of Reaper 6.21.129-dev, and I'm on a rolling distro (PC Linux OS). So either Reaper has some temp error in itself, or I'm missing some libs in my distro. Reaper LV2 development seems to be in a rapid phase, so that bit will be fixed soonish.

By the way, Guitarix plugins are great!!! Sound is very subJective, but the possibilities with these plugins are endless! Thanks Brummer!

**Comment by brummer10** [comment]
You are welcome.
Nice to see Reaper including LV2 support.
