### ISSUE TITLE
[Feature request] Mute when tuning

### ISSUE THREAD

**Issue by davidebasilio** [brummer10/guitarix#52]
I find the tuner plugin super handy, but  I haven't found a way to mute the output when tuning, which can be quite annoying.
Is that possible and I simply haven't figured out how to do it?
If not, would it be hard to implement?

Thanks!

**Comment by brummer10** [comment]
Hi
You could press the space bar to mute the engine, the tuner will still be alive.

regards
hermann

**Comment by davidebasilio** [comment]
Mhh OK, so keep the tuner always on and simply mute everything when tuning.
Yeah, sounds like a good suggestion, I guess that keeping the tuner on doesn't really cause any issues.
Thanks for the quick reply!
