### ISSUE TITLE
 failed to lock memory: Cannot allocate memory

### ISSUE THREAD

**Issue by FabioNevesRezende** [brummer10/guitarix#54]
I've already used guitarix in other distros (Debian, Artix) but now (on Archlinux) I'm having error trying to use it.
When I start the program (with jackd already runnig through QJackCtl as I always did and worked) it fails wit this error messages:

> [16:17:43]  system init  ***  mlockall failed: [16:17:43]  system init
>
> ***  failed to lock memory: Cannot allocate memory 
>[16:17:43]  system init  ***  failed to lock memory: Cannot allocate memory [16:17:44]
> 
> loaded state  ***  from file /home/fabio/.config/guitarix/gx_head_rc
>
> [16:17:44]  Jack init  ***  The jack sample rate is 48000/sec
>
> [16:17:44]  Jack init  ***  The jack buffer size is 1024/frames ... 
>
> [16:17:44]  PitchTracker  ***  error creating realtime thread - tuner
>
> not started

I've already added my user to the `audio` group and restarted but the error remains.

**Comment by hfiguiere** [comment]
you say you have used it on other distro, but you didn't tell which one it is this time.

**Comment by FabioNevesRezende** [comment]
debian and artix linux @hfiguiere 
now I'm using ArchLinux

**Comment by FabioNevesRezende** [comment]
@hfiguiere I've edited and added the distros

**Comment by hfiguiere** [comment]
Apparently ArchLinux needs to be added to a `realtime` group.

https://wiki.archlinux.org/index.php/Realtime_process_management
https://wiki.archlinux.org/index.php/Professional_audio

**Comment by FabioNevesRezende** [comment]
yup, that solved the problem, thanks
