### ISSUE TITLE
Can't access to own presets when starting guitarix with NSM

### ISSUE THREAD

**Issue by sub26nico** [brummer10/guitarix#55]
Hi,
I encounter an issue when i launch guitarix with NSM (and also with RaySession), guitarix doesn't show presets i made with the standalone ( outside NSM). And if I made a preset in NSM, it doesn't appear in the preset list of the Jack app. It could be very useful to have access to the presets made previously inside or outside NSM.

**Comment by brummer10** [comment]
Hi
Yes, it's a pity. I'm not absolutely sure how to solve that. Sure, I could just keep the default preset directory even when under NSM control, just that will introduce other issues, like loaded external plugins not loaded, etc. At least it will mean that we just need to keep the config files in the default directory. 
Main issue then will be that sessions cant be shared.
A workaround for now maybe to import the presets you wont to use in the session by drag'n'drop them from ~/.config/guitarix/banks into the guitarix preset window.

**Comment by sub26nico** [comment]
Thanks for the reply and for the tip, it seems to work, drag'n'drop 'mybankfile.gx' in the UI preset window make appears my own preset/bank in the bank list.
