### ISSUE TITLE
gxts9.lv2 modgui is currently empty / not showing correctly

### ISSUE THREAD

**Issue by MaxPayne86** [brummer10/guitarix#59]
So I'm testing Guitarix 0.42.1 on Aida DSP OS. What I've found are a lot of positive things, for example the multitrack looper is a killer and I'm having fun playing with it! At the same time one of the pedals I use very often such as the gxts9.lv2 has a missing/broken modgui graphics. I've tried the one available here

https://github.com/moddevices/mod-lv2-data.git
8288478857983609e6dd32c2351b72cb44b0a3af

but substituting the ttl of guitarix with the ones from there, when loaded the plugin makes the interface to crash. I've tried to merge them (ttls from guitarix and modgui from lv2-data) and it seems to work although it's displaying a wrong screenshot (but the thumbnail graphics seems ok).
I don't know if the reason is the guys from moddevices are not fast enough to cope with the guitarix release rate or whatever, it seems they're stuck with a very old version of guitarix in their system. I understand that for guitarix developers taking the burden of maintaining this interface is a pain. So it seems nobody is winning here.
I'll try to propose to them (moddevices) the following solution: render the graphics from the infos in the ttl. I mean for things like background color we can add a directive in the ttl. In this way plugins always look decent even if a true interface is not available. Any comment much appreciated!

**Comment by falkTX** [comment]
the moddevices repo is intentionally old, as to maintain the current plugins without change.
so the ttl data in that repo belongs to an old version.

fixes are backported when something is known to be broken.
you can see a few of them at https://github.com/moddevices/mod-plugin-builder/tree/master/plugins/package/guitarix

for moddevices, plugins are not updated unless they have a reason to.
so far things work fine as far as I know, so we leave them alone.

**Comment by brummer10** [comment]
as I already mentioned in the mod devices forum, it is by far not true for the gx_live_looper. This one have never worked nicely on the MOD, but do now. Also other plugs receive updates in the last past years which makes them by far better then what is now presented by the MOD to there users. I think, it's a pity that mod devices still deliver the old versions. They work, true, and they will work properly for ever, but they are not the best what mod devices could deliver to there users.
It was a bad decision to fork guitarix and stay with the old, never updated plugs. Still, there is nothing I could do for this, so, please forward this bug to Mod, will close it here now.

**Comment by falkTX** [comment]
@brummer10 there is nothing strictly saying we cant update the plugins.
but if/when that happens, it needs to be done carefully, one by one

I am all for updating them, but us being a very small team we are always lacking in time for stuff like this.
that said, renaming the current mod-plugin-builder package as guitarix-old and slowly bring in the new builds would be great.
is the live looper plugin on the stable/prod plugin store, or only in "beta" ?
we can start with that plugin if you think it will be useful for MOD users.

**Comment by MaxPayne86** [comment]
@falkTX @brummer10 I've decided to update guitarix because of the looper and because I've noticed the script that solves the circuits is updated often, that leads to updates in the static non-linearities that are directly affecting the sound of the effects. This is actually where the "magic" happens. Another thing I've noticed is there are some new plugins. I think Mod Duo users would love the new release. I've tested some of them on Aida DSP OS and are working, despite the graphics the gxts9.lv2 is working perfectly. I use yocto to build all the plugins but I can share my conf settings and everything else related to this bundle.

**Comment by MaxPayne86** [comment]
@falkTX my opinion is that modgui is great but is also a source of problems since it requires to be updated together with the source code but it's difficult to ask the developers of an open source bundle to maintain it. And the risk is to stay with old version of plugins just because you have to plan the work on the graphics. I see the graphics on modgui is more or less the same for every pedal I was trying to figure out what can work for you
- a default graphic for the plugin which is just nicer than the actual one + some entries in ttl that decide the color for the pedal (rgb code)
- a generator that builds the graphics by parsing the ttl (the evolved version of the current wizard)
I can move the the mod forums of course
