### ISSUE TITLE
[Feature Request]  fizz-remover

### ISSUE THREAD

**Issue by gitterdude** [brummer10/guitarix#65]
Most virtual amps, including Boss GT and Line6 pedal boards, have a fizz in the distortion. It's been described as "angry bees".

The Radtone Harmonic Converger was made and sold as a solution to the pedal board problem but a simple solution in the software world is to add a notch filter to tame the obnoxious frequency.

In the attached example I'm using the LSP Parametric EQ 16 with a notch filter at 5556 Hz, Q = 8.5 and Gain = -8.5 between the gx_head_fx outs and Jack's playback inputs and flip between the EQ being Off and On.

It would be neat to have this feature built in; either as a pedal or as a switch somewhere, since I bet some people like the fizz.

[Guitarix-LSP-ParamEQ16.mp3.zip](https://github.com/brummer10/guitarix/files/6371961/Guitarix-LSP-ParamEQ16.mp3.zip)

**Comment by brummer10** [comment]
Well. yes, very notable. Very nice suggestion. We've set the notch at 6543 Hz right now, but it seems a additional notch at  5556 Hz like you suggested does wonders. Great!!
Moves on top of my to do list!
regards
hermann

**Comment by brummer10** [comment]
So, done, there is now a little switch in the main amp box to enable/disable a Anty Fizz plugin.

**Comment by gitterdude** [comment]
Tested and approved.
Thanks.
