### ISSUE TITLE
Guitarix still requires python 2.7 to build

### ISSUE THREAD

**Issue by hfiguiere** [brummer10/guitarix#66]
You can't build Guitarix from git without having python 2.7

Python 2.7 has been deprecated for a while now.

`libgxwmm/gxwmm/wscript` require `pygobject-2.0` and then call `python2` explicitely.

**Comment by gitterdude** [comment]
It builds fine on Ubuntu 21.04, which doesn't have python2 by default.

**Comment by hfiguiere** [comment]
`--generate-cpp-wrapper ` is what triggers it

**Comment by gitterdude** [comment]
To be fair, the help info for --generate-cpp-wrapper clearly states `(Developers only!!)`

**Comment by hfiguiere** [comment]
Tell me about it.

Python 2.7 is still deprecated.

**Comment by brummer10** [comment]
what we do is call  `generate_wrap_init.pl` which is part of glibmm. This one requires python 2.7, unfortunately. 
But true is, you'll never ever require that to build guitarix, more over, it is discouraged to do so. (Developers only!!)
@hfiguiere if you work on gxlib/mm let me know, and I'm sure we find a way to implement what you are looking for. 
regards
hermann

**Comment by hfiguiere** [comment]
`.pl` is Perl

**Comment by hfiguiere** [comment]
the tl;dr, it want pygobject2 for h2def.py, which is run explicitely using python2.
h2def.py exists with recent glibmm, albeit it doesn't seem to be installed anywhere.

**Comment by brummer10** [comment]
Ah, yes, true it's h2def.py we call. 
True is, it wouldn't work with pygobject-3.0 and python3 as there is no h2def.py in there. So what should we do?

**Comment by hfiguiere** [comment]
I think the approach I was looking at is to copy the glibmm version of the scripts and use them.
