### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Rippert** [brummer10/guitarix#69]
So, as I learn more about the intricacies of Guitarix, I need to start writing this stuff down. I remember Hermann was asking for help with documentation somewhere, so is there any consensus on what format the documents should be in?

**Comment by brummer10** [comment]
I guess it depend on how we present it. So, as part of the github repository it would properly be nice in the markdown format, as part of the source distribution it may be nice in plain text, or in html format, anyhow, any documentation, which format however is welcome and better then non documentation.

**Comment by Rippert** [comment]
What do you think about using the GitHub WIKI? it's basically just a bunch of markdown pages and is also a separate project page that you can push and pull through git. I haven't really worked with it, but it sounds potentially useful.

**Comment by brummer10** [comment]
Yes, good idea. I've as well never work with the github wiki pages.
