### ISSUE TITLE
Error when compiling using lv2 1.18.0

### ISSUE THREAD

**Issue by Jacalz** [brummer10/guitarix#7]
i was trying to compile guitarix v0.39.0 using the latest lv2 release, but the compile fails with this error:
<pre><font color="#4E9A06">Waf: Leaving directory `/home/build/YPKG/root/guitarix/build/guitarix-0.39.0/build&apos;</font>
<font color="#CC0000"><b>Build failed</b></font>
<font color="#CC0000"><b> -&gt; task in &apos;gx_amp_gui&apos; failed with exit status 1 (run with -v to display more information)</b></font>
<font color="#CC0000"><b> -&gt; task in &apos;gxautowah_gui&apos; failed with exit status 1 (run with -v to display more information)</b></font>
<font color="#CC0000"><b> -&gt; task in &apos;gx_amp_stereo_gui&apos; failed with exit status 1 (run with -v to display more information)</b></font>
</pre>

I think this might be due to to deprecated functions in LV2 or something along those lines. I see a lot of references to [-Wdeprecated-declarations] in the terminal output.

**Comment by hfiguiere** [comment]
you actually truncated the error.

**Comment by brummer10** [comment]
Please clone guitarix from the git repository. 
The latest release files didn't fit any more with the latest LV2 release.

**Comment by Jacalz** [comment]
> you actually truncated the error.

Yeah I know, sorry. It happened to be way outside how far I could scroll back in my terminal, overshadowed by thousands of recommendations from gcc flags like -Wdeprecated-declarations adn other stuff.

Thanks @brummer10. Will try the git repository.

**Comment by Jacalz** [comment]
Master seems to work fine. Any plans of releasing a new version soon? @brummer10 
I am packaging for Solus and it is much preferred to use releases over git tags.

**Comment by brummer10** [comment]
Yes, we would love to do a release soon, just, we've some stuff to sort out before, so I really don't know how long it takes.
