### ISSUE TITLE
Something strange with guitarix hide optional gui under NSM

### ISSUE THREAD

**Issue by Houston4444** [brummer10/guitarix#70]
This is very weird, but it seems to be this:

Guitarix doesn't hides its GUI when it receives `/nsm/client/hide_optional_gui` if the Guitarix window is totally covered by another window. Its optional gui state is still visible, and factually, its GUI is still here.

I precise I am under Librazik 3, with KDE plasma (X11).

More weird ! If I activate KDE Plasma desktop effects, the guitarix show/hide GUI works normally.

This is not very strong, I suspect something with systray.

Cheers. Mathieu

**Comment by brummer10** [comment]
Looks like a desktop manager thingy. It seems that KDE marks a window as hidden when no part of it is visible, so a call to widget_hide() will be ignored by the desktop manager. 
When effects been enabled, windows could be transparent, so the desktop manager handle it different and didn't mark windows as hidden when they are fully overlapped by other windows, as they could still be visible. 
Still, I don't have KDE installed, so I could only guess, but I doubt that it has to to with the systray at all.

**Comment by Houston4444** [comment]
I suspect the systray because I wonder why Guitarix is the only one application I see with this bug (and it uses systray). But I've got no GTK3 other application example (with NSM support with optional-gui).
It may happens in rare conditions (on KDE... without desktop effects...), and this is not strong, user can still hide the GUI closing Guitarix window.

So let's forget this problem ;)

**Comment by grammoboy2** [comment]
I seem to have a similar problem. If Guitarix gets the hide gui signal after replying to open, it doesn't hide. It sends it gui state shown, twice after launch. Why twice? Why not hidden?

I'm able to hide the gui from the NSM gui, so there is something going wrong at launch/open.

Does guitarix hides it gui at first launch? 
Does guitarix stores it gui state in a session?

**Comment by grammoboy2** [comment]
I've a similar problem. In a tiling window manager, when Guitarix is not the visible one, I can't hide it. At launch the server gets the message gui shown twice here.

Maybe something wrong here?
https://github.com/brummer10/guitarix/blob/375518bc7e6271929005a45d8129ef54e8d3ea2a/trunk/src/gx_head/gui/gx_main_window.cpp#L2431

**Comment by grammoboy2** [comment]
Can't reproduce atm. I'll keep an eye on it and will report when I hit the problem again.
