### ISSUE TITLE
system init *** mlockall failed: system init *** failed to lock memory 

### ISSUE THREAD

**Issue by Velnbur** [brummer10/guitarix#72]
Distro: Fedora 34 with Gnome 40

`groups` output:
`velnbur wheel audio docker`

![Знімок з 2021-05-30 19-44-13](https://user-images.githubusercontent.com/64193423/120113520-891a2280-c183-11eb-815f-13b82837cc52.png)

**Comment by gitterdude** [comment]
What does  `ulimit -a` say?
"max locked memory" should be unlimited or at least a few hundred MBs and "real-time priority" should be over 90

If not then make sure you have the correct lines for the audio group in /etc/security/limits.conf or in a file in /etc/security/limits.d and that you've rebooted or logged out and in again after adding your user to the audio group.

**Comment by NathanPB** [comment]
I think you need to be in the ``realtime`` group too

**Comment by evbo** [comment]
@gitterdude I am gettting it on Ubuntu 20.04:
>  ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31130
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31130
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

What is the suggested solution? @NathanPB I don't understand what you mean? Do I need to add my user to a group?

**Comment by NathanPB** [comment]
@evbo yeah, you run `sudo usermod -a -G realtime your_user`

https://www.howtogeek.com/50787/add-a-user-to-a-group-or-second-group-on-linux/

**Comment by evbo** [comment]
@NathanPB thanks, that group didn't exist but I created it. Then I needed to add my user to the `audio` group as well. Finally, works!

**Comment by FotiadisM** [comment]
what worked for me was, `usermod -aG audio,realtime <user>`, create the file `/etc/security/limits.d/99-realtime-privileges.conf` with the contents of:

```
@realtime       -       memlock         unlimited
@realtime       -       rtprio               95
@realtime       -       nice                  -11
```
