### ISSUE TITLE
Doesn't install on Raspberry Pi (Manjaro)

### ISSUE THREAD

**Issue by slavikator** [brummer10/guitarix#74]
I don't know if Guitarix should work on ARM. In my case, it cannot be installed because of unresolvable dependence.

Manjaro is up to date.

```
sudo pacman -S guitarix
resolving dependencies...
warning: cannot resolve "libboost_iostreams.so=1.75.0-64", a dependency of "guitarix"
:: The following package cannot be upgraded due to unresolvable dependencies:
      guitarix
```

**Comment by hfiguiere** [comment]
This is a distribution problem since you are using pacman.

**Comment by slavikator** [comment]
The issue was resolved after the next system update.
