### ISSUE TITLE
 Full CPU in guitarix --nogui 

### ISSUE THREAD

**Issue by fernando-inf** [brummer10/guitarix#75]
Debian Bullseye- Guitarix 0.42.1
Hello, when I open guitarix --nogui, I have a 100% consumption of one of the CPU cores. In GUI mode it only consumes 10%. I have installed guitarix from the Debian Bullseye repositories, thanks

**Comment by brummer10** [comment]
Hi
I've found and fix this issue.

**Comment by fernando-inf** [comment]
Thanks.
