### ISSUE TITLE
Metronome level is too low

### ISSUE THREAD

**Issue by slavikator** [brummer10/guitarix#76]
Even with the gain knob at maximum, I can barely hear it (when playing). The main guitar signal is far from touching the limiter.

Is there a way to turn up the metronome? Am I missing something?

**Comment by gitterdude** [comment]
The best way to get a decent volume out of the metronome is to place directly below the amp in the Order tab.
You may also need to disable the noise gate, since the metronome is affected by it.

It would be nice if the metronome bypassed the entire sound stack, other than the master volume, and if one could change the actual sound of the click.
The frequencies of the current marimba (?) sound are in the same range as the distorted guitar sounds so it's still hard to hear it while playing, even with a decent click volume.

**Comment by slavikator** [comment]
I have tried it below the amp and it is too quiet. If I put it above everything I can manage the decent volume but then I cannot record without the metronome clicks. And yes, the current sound is very hard to hear at any level.

**Comment by brummer10** [comment]
I've made it a way louder now, let me know if it is loud enough. And yes, it's a marimba.

**Comment by gitterdude** [comment]
Yes, it is way louder now; to the point that it starts distorting really quickly.

It works. and I'm not using it myself so I really don't care, but I would suggest selecting a sound other than the current mid-rangy marimba.

The basic problem here isn't so much the volume itself but more the frequencies involved. 
The marimba lives in the same audible spectrum as the distorted guitar and that means that they're competing for attention.
I'd suggest changing the sound to a more percussive one; something like a snare or a hi-hat.

**Comment by brummer10** [comment]
Alternatively you could use the Drum Sequencer and setup your own metronome. This one have as well a option to bypass the effect chain.

**Comment by slavikator** [comment]
Nothing really changed. If I put it after the main amp I cant hear the metronome at all. The only way to get it to work is to decrease the input level (drastically) on the main amp. The master volume of the main amp affects the metronome volume even if it goes after that amp. Thinking logically it shouldn't. 

But, at least, when you record something using the metronome and then import that recording into Ardour the tempo is well synchronized. 

I have tried Drum Sequencer for that purpose (no issues regarding volume level) and the recorded track with a tempo of 125 doesn't match with the tempo of Ardour. 

I really would like to use Drum Sequencer for recording some ideas and then import them to Ardour. It is much more comfortable to play with it than with a metronome. But the tempo of Drum Sequencer just doesn't match with the tempo of Ardour.

**Comment by slavikator** [comment]
> Alternatively you could use the Drum Sequencer and setup your own metronome. This one have as well a option to bypass the effect chain.

Is Drum Sequencer able to load custom sounds? I didn't find a way to do it.

**Comment by slavikator** [comment]
> I've made it a way louder now, let me know if it is loud enough. And yes, it's a marimba.

I think the issue isn't in the metronome itself but in the inability of setting the volume independently of the main amp (or all the chain). Maybe an option to bypass the effect chain as on the Drum Sequencer would be a solution?

**Comment by brummer10** [comment]
After you reported I found a little issue in the drum sequencer timer. Hopefully it will sync now with ardour. 
You can't load a sample in the drum seq, all sounds been synthesized. 

Adding a direct out option to the metronome would properly be the best option, only I've currently not the time to do it.
