### ISSUE TITLE
GX-plugins

### ISSUE THREAD

**Issue by slavikator** [brummer10/guitarix#77]
![Screenshot_20210806_143811](https://user-images.githubusercontent.com/18514413/128505732-ec957cef-ba68-4086-aede-35f8e8edb0e3.png)

Is it possible to reproduce this chain with the lv2 plugins in Ardour? 

Rat
JCM800Pre
Tonestack
Poweramp
Cabinet

I couldn't find in the GX-plugins the Poweramp and Tonestack. Also, there is no way to disable the preamp section in the GXAmplifier if I use GXjcm800pre (like I do in the Guitarix standalone version). I think I don't need the main amplifier at all.

**Comment by brummer10** [comment]
Indeed, I haven't done the Tonestack and Poweramp port to LV2. I really need to do it.

**Comment by slavikator** [comment]
So, at least one person is waiting for it. Thanks for your work.

Another story about the standalone version - why isn't possible to disable completely the main amp? It is useless if you use JCM pre + Tonestack + Poweramp.

**Comment by brummer10** [comment]
Guitarix is build around the main amp. At least you could disable it by select the "--" tube setting. You can't unload the UI, as it still act as master gain and master volume. It present the VU meter, the limiter, Bass Boost, Presence and Reverb. So it is not completely useless. We've added the "--" option to allow the use of other amp simulations instead the inbuilt one, just when we wrote guitarix back then there wasn't any at all for linux. This day's you've fortunately some choices.

**Comment by slavikator** [comment]
> Guitarix is build around the main amp. At least you could disable it by select the "--" tube setting. You can't unload the UI, as it still act as master gain and master volume. It present the VU meter, the limiter, Bass Boost, Presence and Reverb. So it is not completely useless. We've added the "--" option to allow the use of other amp simulations instead the inbuilt one, just when we wrote guitarix back then there wasn't any at all for linux. This day's you've fortunately some choices.

You are right - VU meter, the limiter, Bass Boost, Presence, and Reverb these staff make sense.

**Comment by slavikator** [comment]
Closed it by mistake. Sorry.

**Comment by kramlie** [comment]
I would appreciate this too!

An alternative/addition, would be to enable both Preamp Model and Presence to be set to Off in GXAmplifier. With this, you could chain two of them together and get the Tonestack before the Preamp. That would be relatively cheap to implement, and would solve all of the above problems except for the Poweramp.

Presence would be nice to set to Off in LV2, because turning it off in the standalone app sounds very different, and there doesn't seem to be a way to do that with LV2.

**Comment by kramlie** [comment]
I'm considering implementing this and contributing it. @brummer10, would that be acceptable? Adding an "Off" setting to the Tube selections, and adding an Off switch for the Presence effect, in the GxAmplifier plugins?

**Comment by brummer10** [comment]
Hi @kramlie 
Yes, that would be appreciated.

**Comment by brummer10** [comment]
Hi @kramlie  
I've done it. You could now switch off the Presence by dial the Presence controller below 1.0 (that will switch the presence off). I also added the option "--" to the tube selector which will switch the tube emulations off, but keep the Pre- and Master- Gain  controls working.

**Comment by kramlie** [comment]
Cool, that was fast! I'll try it out as soon as possible!

**Comment by kramlie** [comment]
@brummer10: It's working beautifully! Thank you!
