### ISSUE TITLE
Live Looper crashes

### ISSUE THREAD

**Issue by slavikator** [brummer10/guitarix#78]
Live Looper crashes on loading large wave file. The file was exported from Ardour in its default format. 

Does it require a specific file format?

**Comment by brummer10** [comment]
No, file loading is supported by libsndfile.
When you could send me the file I'll investigate. (Maybe it is just to large and the looper fail to acquirer the buffer)

**Comment by slavikator** [comment]
> No, file loading is supported by libsndfile.
> When you could send me the file I'll investigate. (Maybe it is just to large and the looper fail to acquirer the buffer)

It is definitely large - the entire track. Do we know the limitation in weight or time?

**Comment by brummer10** [comment]
The max size is 4194304 samples
