### ISSUE TITLE
WEBUI don´t work with Python 3 

### ISSUE THREAD

**Issue by fernando-inf** [brummer10/guitarix#79]
It should be added in the README of `guitarix/trunk/webui/ `that WEBUI does not work with python 3, python 2.7-minimal must be installed and thus start the server with python2.7 inside the `websockify` folder:
`python2.7 websocketproxy.py --web = .. / '*': 8000 127.0.0.1:7000 `

**Comment by brummer10** [comment]
Yes, that is true. It may require some work to make the included websockety app compatible with python3.

**Comment by OddBloke** [comment]
I hacked an Ansible playbook together to run guitarix on an RPi, and I have a quick-and-dirty patch inline there which has got me unblocked: https://gist.github.com/OddBloke/bc0c13f7b65095ae52ed23d94e659fbf

**Comment by brummer10** [comment]
Hi, thanks a lot @OddBloke . Still here on debian/sid it requires some more fixes, but your patch get me going.

**Comment by fernando-inf** [comment]
Hi, I have compiled Guitarix today and notice that WEBUI already works with python 3, so this problem is fixed.

However I see that the selection of Banks is not available, I attach a video: https://youtu.be/QXt0s6PrVjo

**Comment by brummer10** [comment]
Strange. Here it works as expected with both (python2 and python3)
From what I could see you running the debug version of the webui, please build the deploy version of the webui and try again.
The connection of the deployed version is much faster because we could cache the UI stuff in the browser. 
If it still don't work with the deployed version, please start the server in verbose mode to get some info what goes wrong (just add -v at the end of the command (after :7000))

**Comment by fernando-inf** [comment]
Hi Brummer, thanks for the help, now it works fine. Although I do not know what the problem was. At first I thought it was because I had many banks. Likewise Run bash deploy.sh, then reboot the machine and it works fine.

On the other hand, I notice in the task manager that python runs doubly, taking up twice the RAM, but only one process uses the CPU, usually at 1%. 
![guitarix-webui](https://user-images.githubusercontent.com/85811973/134689611-c651d685-3222-4a71-912b-3b7e38944445.png)

**Comment by brummer10** [comment]
> On the other hand, I notice in the task manager that python runs doubly, taking up twice the RAM, but only one process uses the CPU, usually at 1%.

Two processes been to be expected, as it use multiprocessing for the worker thread. 
However, you've to take the memory usage shown in the process table with a grain of salt, as the memory (for the static data) is mostly shared between both processes, so the real memory usage of both processes is lower then shown by the process table.
