### ISSUE TITLE
Unnatural decay at high gain (palm mutes)

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix#82]
I'm back to Guitarix after a few months off, and found another oddity in my old metal presets (latest git: 0.42.1.r25.g28374920).
When doing palm mutes, the sound decays in three steps:
1 - Note decay
2 - Complete silence (like there's a noise gate kicking in)
3 - Then the expected bakground noise starting after ~1s.
This sounds very unnatural for chugs and palm mutes. example [There](https://drive.google.com/file/d/1efso7M5MPT8Be5U2fHgsjGhPm5UANoBA/view?usp=sharing)

The expected behavior is that the notes would decay into background noise, like on an analog amp.
This seems to have to do with the amp itself (the noise gate is of course disabled), and as far as I remember there was no such issue one year ago.
I attached the preset bank in question. Any of the first 4 presets shows the problem.

[Gimmeapill.gx.zip](https://github.com/brummer10/guitarix/files/7196366/Gimmeapill.gx.zip)
.

**Comment by Gimmeapill** [comment]
Hi Hermann,
You mean the fix for [#45](https://github.com/brummer10/guitarix/issues/45)?
Maybe. That could be the limiter release being audible, but then there is no audible or visual indication that the limiter ever kicks in to begin with.
In the presets, I'm pushing the pregain, drive + presence to the max on the amp, but the master volume is kept in check between -20/-30 and I never see the limiter bar lighting up unless I get it to clip on purpose.

br,

lx

**Comment by brummer10** [comment]
It seems I found the culprit, looks like the dcblocker I've implemented in the tube emulation leads to this behaviour. 
It's in /trunk/src/faust/guitarix.lib line 93:
`tubestageF(tb,vplus,divider,fck,Rk,Vk0) = anti_aliase : tube : dcblock with {`
change it to 
`tubestageF(tb,vplus,divider,fck,Rk,Vk0) = anti_aliase : tube with {`
and rebuild to check it out.
Now I need to remember why I've introduced that one at all.

**Comment by brummer10** [comment]
Ah, I found why I've done that, and now revert it to the previous implementation. 
#29 
Should be fixed now with a fresh checkout.

**Comment by Gimmeapill** [comment]
Yes, that was it!
The sound is also better altogether - thanks for the great support :-)

**Comment by Rippert** [comment]
Hey Hermann, It looks like you undid the changes from #22, in addition to those from #29. I haven't tested this yet, but the changes in #22 were specifically to keep more of the low end in the signal for Bass players. The dcblocker from #29 was a separate issue with inaudible noise below 20 Hz causing overloads in the signal chain.

I've been out of things for a while, so it will take me some time to set up an A/B test to see how this affects my Bass tone. If the high pass filters from #22, are causing tone degradation for Gimmeapill, maybe there is some compromise between removing them completely and having them set at 31 Hz, which is right at the low B string tuning on a five string Bass. Maybe 10 Hz?

**Comment by brummer10** [comment]
Ah, that was it. 
So now I've implemented the switch to select between "High Gain and Low End". It default to use the High Pass Filter at 31Hz, and could be switched to use the dcblockerat() to enable the Low End.

**Comment by Gimmeapill** [comment]
Just tested and I can confirm that the switch works as expected - also that removing the high pass filter does make the decay issue come back, but that's fine with me.
Could you maybe just make the button the same size as the BassBoost, Presence & Reverb?
This one as well as the anti fizz are really hard to click on a hidpi screen.

**Comment by fernando-inf** [comment]
Hello Gimmeapill, I have downloaded your Bank, I notice that there is a noise when going from the preset "Metal-HM-2" to "Doom-Basic" and from "Bass Crybaby" to "Bass-FF Mayer Crybaby". I think the culprit is the FUZZ FACE MAYER shelf. The noise occurs when going to all the presets that have that rack, perhaps it should be reported as a Bug.

**Comment by brummer10** [comment]
So I've added padding to the new switches to give them the same size then the other ones. 
To the Fuzz Face Mayer, well, I need to redo it, I know, . . . will come soon.

**Comment by Gimmeapill** [comment]
Thanks Hermann, the buttons are way more usable now.
No hurry as far as I'm concerned, I have a solid HW equivalent to the FF so it's no big deal.
I will probably go again through the effects list (both internal and LV2), as I remember finding some oddities a few months ago...
