### ISSUE TITLE
Limit assignment of some MIDI CC.

### ISSUE THREAD

**Issue by fernando-inf** [brummer10/guitarix#84]
Hi, I think they should limit the assignment of some MIDI CC. I recently downloaded a preset, and it had an effect assigned to a MIDI CC32. This caused that when selecting this preset, a wrong bank number would be shown on the display of my Pedalboard. 

<img src="https://scontent.fsla1-1.fna.fbcdn.net/v/t1.6435-9/241277159_4517448554941981_2591775891527218632_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=730e14&_nc_ohc=F5d11UDDi4cAX-oC2Dn&_nc_ht=scontent.fsla1-1.fna&oh=031662439a62b4459addd284e2a3a2ad&oe=616DAF67">< /img>

**Comment by brummer10** [comment]
That's indeed critical. However, you could easily change that to use a more common CC. I don't think that we need to implement a limit for that case. That must anyone decide for himself.

**Comment by fernando-inf** [comment]
Okay, I understand your position. I think at least CC32 and CC0 should be limited. I leave it to your discretion whether or not to close this "Issue". Greetings.
