### ISSUE TITLE
cycling through cabinets/pre-amps/tubes is skipping items

### ISSUE THREAD

**Issue by MyLoFy** [brummer10/guitarix#94]
This issue seems to affect the following lv2 plugins of the guitarix package:

- GxAmplifier-X
- GxAmplifier-Stereo
- GxCabinet

When cycling through the different cabinet/pre-amp/tube items I realized that the sound only seems to change every second or third item. So apparently not all listed cabinets/preamps/tubes can be selected and it is unclear which setting is active.
In the guitarix standalone application it works as expected.

Screencast: https://mark.nl.tab.digital/s/6GdFZCeQBH97Dq3

Guitarix version 0.42.1.r39.g84641a37-1
OS ArchLinux

**Comment by brummer10** [comment]
Hi
Thanks for reporting. I could reproduce and fix the issue. Please checkout from git repository and let me know if the latest version solved the issues you reported.
regards
hermann

**Comment by MyLoFy** [comment]
thanks! just tested the latest version and it's also resolved on my end.
